<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FromArtisanSupremecourtsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('supremecourts')->delete();
        
        \DB::table('supremecourts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Naxçıvan Muxtar Respublikası Ali Məhkəməsi - 90',
                'slug' => 'naxcivan-muxtar-respublikasi-ali-m-hk-m-si-90',
                'content' => '<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt; break-after: avoid;"><span style="box-sizing: border-box; font-size: 14pt;">Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi uzun və şərəfli bir tarixi inkişaf yolu ke&ccedil;mişdir. Bu yol Nax&ccedil;ıvan Muxtar Respubli&shy;ka&shy;sının, b&uuml;t&ouml;vl&uuml;kdə isə Azərbaycanın h&uuml;quq tarixi ilə bağlı olub &ouml;lkəmizin və muxtar respublikamızın ke&ccedil;diyi &ccedil;ox m&uuml;rəkkəb və əlamətdar tarixi hadisələrlə zəngin bir d&ouml;vr&uuml;n&uuml; &ouml;z&uuml;ndə təcəss&uuml;m etdirir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Tarixi mənbələrə əsasən demək olar ki, Nax&ccedil;ıvan MSSR-də Azərbaycan SSR Ali Məhkəməsinin b&ouml;lməsi Azərbaycan SSR Mərkəzi &nbsp;İcraiyyə Komitəsi Rəyasət Heyətinin 3 oktyabr 1925-ci il tarixli qanunu ilə&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">yaradılmışdır. Bu məhkəmənin təsis edil&shy;məsi və səlahiyyətinə daxil olan məsələlərin dairəsi onu Nax&ccedil;ıvan Muxtar Respublikası &nbsp;Ali Məhkəməsinin &ldquo;sələfi&rdquo; kimi qiymətləndir&shy;məyə və beləliklə, Ali Məhkəmənin yaranma tarixi olaraq məhz 1925-ci il 3 oktyabr tarixini qəbul etməyə əsas verir.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">1934-c&uuml; ildən Nax&ccedil;ıvan MSSR Baş Məhkəməsi, 1937-ci ildən isə Nax&ccedil;ıvan MSSR Ali Məhkəməsi adlandırılan bu məhkəmə sonrakı d&ouml;vrlərdə ciddi struktur dəyişikliyinə uğramamış və ona aid edilmiş işlərə birinci və yuxarı instansiya&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">məhkəməsi qismində baxmaq, habelə fəaliyyəti dairəsində olan məhkəmələr &uuml;zərində məhkəmə nəzarətini həyata ke&ccedil;irmək funksi&shy;ya&shy;la&shy;&shy;rına malik olmuşdur.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">1977-ci ildə SSRİ-nin yeni Konstitusiyasının qəbul edilməsi ilə bağlı Azərbaycan SSR-in məhkəmə orqanları sisteminin statusunu tənzimləyən qanunvericiliyin də dəyişdirilməsi zərurəti yaranmış, nəticədə 1981-ci ilin iyun ayının 16-da &ldquo;Azərbaycan &nbsp;SSR-də məhkəmə quruluşu haqqında&rdquo; yeni Qanun qəbul olunmuşdur. Həmin qanunda Nax&ccedil;ıvan MSSR Ali Məhkəməsinin səlahiyyətləri daha da genişləndirilmişdir. 26 iyun 1990-cı il tarixdə &ldquo;Azərbaycan SSR-də məhkəmə quruluşu haqqında&rdquo; Qanun qəbul edilmiş və bu Qanunla 1981-ci il tarixli qanunda təsbit edilən qaydalar daha da təkmilləşdirilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14pt;">1990-cı ilin əvvəllərindən başlayaraq&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">SSRİ-də, o c&uuml;m&shy;lədən</span>&nbsp;Azərbaycan&shy;da cərəyan edən hadisələr, ən başlıcası 18 oktyabr 1991-ci ildə Azər&shy;baycan Respublikasının d&ouml;vlət m&uuml;stəqilliyini əldə etməsi məhkəmə quru&shy;luşunun, ədalət m&uuml;hakiməsi qaydalarının k&ouml;kl&uuml; şəkildə&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">dəyişdirilməsi və məhkəmələrin m&uuml;stəqilliyinin təmin edilməsi zərurətini ortaya &ccedil;ıxarmış, lakin həmin d&ouml;vrdə digər sahələrdə olduğu kimi məhkəmə orqanları sistemin&shy;də də aparılan dəyişikliklər</span></span><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">yetərli olmamışdır.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Yalnız 1993-c&uuml; ildə Ulu &ouml;ndər Heydər Əliyevin hakimiyyətə qayıdışı ilə b&uuml;t&uuml;n sahələrdə olduğu kimi məh&shy;kəmə hakimiyyəti sahəsində də k&ouml;kl&uuml; islahatların b&uuml;n&ouml;vrəsi qoyulmuşdur. Demokratik d&ouml;vlət quruculuğunun əsas hədəflərini m&uuml;əyyən edən Ulu &ouml;ndər demişdir:&nbsp;<span style="box-sizing: border-box; font-weight: bold;"><em style="box-sizing: border-box;">&ldquo;Biz h&uuml;quqi d&ouml;vləti, demokratik d&ouml;vləti yaradırıq. Bunun da ən prinsipial bir hissəsi məhkəmə sistemində islahatların&nbsp; ke&ccedil;irilməsi, onun beynəlxalq h&uuml;quq normalarına uyğunlaşdırılmasıdır&rdquo;</em></span>. Məhz Azərbaycan xalqının &uuml;mummilli lideri Heydər Əliyevin bilavasitə təşəbb&uuml;s&uuml; və&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">rəhbərliyi ilə hazırlanmış, 12 noyabr 1995-ci ildə&nbsp;</span>qəbul edilmiş m&uuml;stəqil Azərbaycan Respublikasının ilk milli Kons&shy;titusiyasında d&ouml;vlət hakimiyyəti qanunvericilik, icra və məhkəmə hakimiyyəti qollarına&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">ay&shy;rılmış, Azərbaycan &nbsp;Respub&shy;likasında məhkəmə hakimiyyətinin ədalət m&uuml;haki&shy;məsi</span>&nbsp;yolu ilə yalnız məhkəmələr tərəfindən həyata ke&ccedil;iril&shy;məsi m&uuml;əyyən olunmuşdur.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Azərbaycan Respublikasında ədalət m&uuml;hakiməsinin qabaqcıl təcr&uuml;bə əsasında həyata ke&ccedil;irilməsinin təmin edilməsi və məhkəmə sisteminin daha da təkmilləşdirilməsi məqsədi ilə 10 iyun 1997-ci ildə &ldquo;Məhkəmələr və hakimlər haqqında&rdquo; Azərbaycan Respublikasının Qanunu qəbul olunmuşdur. Həmin qanunun 10-cu fəsli Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin statusunun tənzimlənməsinə həsr olunmuşdur.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Konstitusiyasının qəbulundan &ouml;tən qısa m&uuml;ddət ərzində Nax&ccedil;ıvan Muxtar Respublikasının Konstitusiyası hazır&shy;lanaraq qəbul olunmuş, 8 yanvar 1999-cu il tarixdən q&uuml;vvəyə minmişdir. Nax&ccedil;ıvan Muxtar Respublikası Konstitusiyasının qəbulu muxtar respublikanın ictimai-siyasi həyatında m&uuml;h&uuml;m əlamətdar hadisəyə&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">&ccedil;evrilmiş, muxtar respublikada d&ouml;vlət idarəetməsinin təşkilinin m&uuml;kəmməl</span>&nbsp;h&uuml;quqi bazasını yaratmışdır. Bu konstitusiyanın məhkəmə hakimiyyətinə həsr olunmuş 4-c&uuml; fəslində Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi &uuml;mumi və ixtisaslaşdırılmış məhkəmələrin icraatına aid edilən m&uuml;lki, cinayət və digər işlər &uuml;zrə ali məhkəmə orqanı kimi təsis edilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin statusu ilə bağlı &ouml;z&uuml;nəməxsus x&uuml;susiyyətlərdən biri onun konstitusiya nəzarətini həyata ke&ccedil;irməsi ilə bağlıdır. Konstitusiyaya g&ouml;rə Ali Məhkəmə Nax&ccedil;ıvan Muxtar Respublikasının ərazisində apelyasiya qaydasında ədalət m&uuml;hakiməsini həyata ke&ccedil;irməklə yanaşı, konstitusiya nəzarətini də təmin edir. Belə ki, Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisi deputatlarının se&ccedil;kilərinin nəticələrinin d&uuml;zg&uuml;nl&uuml;y&uuml;n&uuml;n yoxlanılaraq təsdiq edilməsi, muxtar respublikanın qanunvericilik aktları arasında uyğunluq məsələlərinin həll edilməsi, məhkəmələr tərəfindən insan h&uuml;quq və azadlıqlarının həyata ke&ccedil;irilməsi ilə bağlı Nax&ccedil;ıvan Muxtar Respublikası qanunlarının şərh edilməsi haqqında m&uuml;raciətlərə baxılması Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin konstitusiya nəzarəti orqanı kimi səlahiyyətlərinə daxildir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">&Ouml;lkəmizdə m&ouml;vcud olan davamlı sosial-iqtisadi inkişaf tendensiyası, ictimai həyatın m&uuml;xtəlif sahələrini əhatə edən yeniliklər məhkəmə sisteminin də təkmilləşdirilməsi işini daim diqqət mərkəzində saxlayır.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Ulu &ouml;ndərin d&ouml;vlət&ccedil;ilik konspesiyasını uğurla davam etdirən Azərbaycan Respublikasının Prezidenti cənab&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.2pt;">İlham Əliyev məhkəmələrin &ccedil;ıxardığı qərarların taley&uuml;kl&uuml; əhəmiyyətini vurğulayaraq demişdir:&nbsp;<span style="box-sizing: border-box; font-weight: bold;"><em style="box-sizing: border-box;">&ldquo;Ədalət hər bir cəmiyyətin inkişafı &uuml;&ccedil;&uuml;n başlıca amillərdən biridir. Hər yerdə ədalət olmalıdır, ilk n&ouml;vbədə, məhkəmə sistemində. &Ccedil;&uuml;nki məhkəmələrdə qəbul edilmiş qərarlar insanların taleyinə təsir g&ouml;stərir&rdquo;</em></span>.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Hazırda&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.2pt;">d&ouml;vlət baş&ccedil;ısı cənab&nbsp;</span>İlham Əliyevin&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">rəhbərliyi altında &ouml;lkəmizdə məhkəmə sisteminin inkişaf etdirilməsi və&nbsp;</span><span style="box-sizing: border-box; letter-spacing: -0.2pt;">m&uuml;asirləşdirilməsi istiqamətində &ccedil;oxşaxəli islahatlar həyata ke&ccedil;irilməkdədir. Belə ki, Azərbaycan Respublika&shy;sı Prezidentinin məhkəmə hakimiyyətinin m&uuml;asirləşdirilməsinə həsr olunan 19 yanvar 2006-cı il tarixli fərmanı məhkə&shy;mə islahatlarının n&ouml;vbəti mərhələyə qədəm qoymasına b&ouml;y&uuml;k təkan vermiş&shy;dir. Bu mərhələdə vətəndaşların h&uuml;quq institutlarına olan tələbatının daha keyfiy&shy;yətlə təmin olunması &uuml;&ccedil;&uuml;n &ouml;lkəmizdə yeni apellyasiya məhkəmələri yara&shy;dılmışdır. Məhkəmə sisteminin təkmilləş&shy;diril&shy;&shy;məsi ilə bağlı Azərbaycan Respublikası Prezidentinin 2010-cu il 15 iyul və 9 avqust tarixli fərmanları ilə regionlarda Ağır Cinayətlər və İnzibati-İqtisadi məhkəmələr yaradılmış, &ouml;lkədə fəaliyyət g&ouml;stərən apellyasiya, ağır cinayətlər, inzibati-iqtisadi və hərbi məhkə&shy;mələrin ərazi yurisdiksiyası m&uuml;əyyənləşdirilmişdir.&nbsp;</span>Həyata ke&ccedil;irilən məhkəmə-h&uuml;quq islahat&shy;ları &ouml;lkəmizin&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.2pt;">digər regionları ilə yanaşı, Nax&ccedil;ıvan Muxtar Respublikasında da fəaliyyət g&ouml;s&shy;tərən</span>&nbsp;məhkəmə orqanlarını əhatə etmişdir. Bu fərmanların qəbulundan sonra Nax&ccedil;ıvan Muxtar Res&shy;publika&shy;sının Ali Məhkəməsinin Ağır Cinayətlərə dair&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">işlər &uuml;zrə birinci instansiya kollegiyası ləğv olunaraq ağır və x&uuml;susilə ağır cinayətlərə baxmaq səlahiyyəti yeni yaradılmış Nax&ccedil;ıvan Muxtar Respubli&shy;kasının Ağır Cinayət&shy;lər Məhkəməsinə verilmişdir. Eyni zamanda Ali Məhkəmədə daha iki kollegiya-iqtisadi m&uuml;bahisələrə dair işlər &uuml;zrə və hərbi məhkəmələrin işləri &uuml;zrə kollegiyalar fəaliyyətə başlamış, muxtar respublikada fəaliyyət g&ouml;stərən b&uuml;t&uuml;n rayon (şəhər) və ixtisaslaşdırılmış məhkəmələrin h&ouml;km və qərarlarından apellyasiya şikayəti və protestlərinə baxılması&nbsp;</span><span style="box-sizing: border-box; letter-spacing: -0.2pt;">səlahiyyəti Nax&ccedil;ıvan Muxtar Respubli&shy;kasının Ali Məhkəməsinə verilmişdir.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">Nax&ccedil;ıvan Muxtar Respublikasında fəaliyyət g&ouml;stərən məhkəmələrin fəaliyyətinin m&uuml;asir tələblər səviyyəsində təşkil olunmasında &ldquo;Nax&ccedil;ıvan Mux&shy;&shy;tar Respublikasında h&uuml;quq institutlarının inkişafı haqqında&rdquo; Azərbaycan Res&shy;publikası Prezidentinin 2 noyabr 2006-cı il tarixli Fərmanı son dərəcə m&uuml;h&uuml;m əhə&shy;miyyətə malikdir. Fərmanın qəbulundan sоnra &ouml;tən m&uuml;ddət ərzində&nbsp;</span><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">Naх&ccedil;ıvan Muхtar Rеspublikası&nbsp;</span><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">Ali Məclisi Sədrinin x&uuml;susi diqqət və qayğısı sayəsində&nbsp;</span><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">muхtar rеspublikanın h&uuml;quq institutlarının inkişaf еtdiril&shy;məsi, məhkəmə</span><span style="box-sizing: border-box; font-size: 14pt;">&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">haki&shy;miyyəti оrqanlarının fəaliyyətinin m&uuml;asir standartlar səviyyəsində qurulması,</span>&nbsp;оnların maddi-tехniki bazasının m&ouml;hkəmlən&shy;dirilməsi istiqamətində m&uuml;h&uuml;m işlər g&ouml;r&uuml;lm&uuml;şd&uuml;r.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">H&uuml;quq institutlarının inkişaf etdirilməsi və məhkəmə orqanlarının maddi-texniki</span><span style="box-sizing: border-box; font-size: 14pt;">&nbsp;bazasının m&ouml;hkəmələndirilməsi istiqamətində muxtar respub&shy;likada fəaliyyət g&ouml;stərən məhkəmələr &uuml;&ccedil;&uuml;n m&uuml;asir tələblərə cavab vеrən in&shy;zibati binaların tikilməsi х&uuml;susi yеr tutur.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">M&uuml;qayisə &uuml;&ccedil;&uuml;n bir faktı qeyd edək ki, 1995-ci ilədək muxtar respublikada məhkəmə orqanlarının inzibati binaları nəinki istifadə &uuml;&ccedil;&uuml;n yararsız halda idi, bu binalar həmin d&ouml;vrlərdə hətta məhkəmələrin balansında belə deyildi. Hazırda isə muxtar respublikamızda fəaliyyət g&ouml;stərən b&uuml;t&uuml;n məhkəmə orqanları &uuml;&ccedil;&uuml;n qabaqcıl meyarları &ouml;z&uuml;ndə ehtiva edən, həm memarlıq, həm də daxili tərtibat və dizayn baxımından ədalət m&uuml;hakiməsinin &ouml;z&uuml;nəməxsus x&uuml;susiyyətlərini əks etdirən inzibati binalar inşa edilib istifadəyə verilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Bu məhkəmə binalarının a&ccedil;ılış məra&shy;simlər&shy;ində Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisinin Sədri cənab Vasif Talıbоv iştirak etmiş, yaradılan şəraitdən daha səmərəli istifadə еdilməsi, h&uuml;quqi maarifləndirmə işlərinin genişləndirilməsi, qanunvericilik aktlarının daha dərindən mənimsənilməsi ilə bağlı hakimlərə və məhkəmə aparatı iş&ccedil;ilərinə m&uuml;h&uuml;m t&ouml;vsiyələr vеrmişdir. Ali Məclisin Sədri bildirmişdir ki,&nbsp;<span style="box-sizing: border-box; font-weight: bold;"><em style="box-sizing: border-box;">&ldquo;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">vətəndaşlara h&uuml;quq və vəzifə&shy;lərinin izah edilməsi,</span>&nbsp;məhkəmə prosesində ədalətli qərarların qəbul edilməsi daim diqqət mərkəzində saxlanılmalıdır&rdquo;.</em></span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">Məhkəmə hakimiyyətinə g&ouml;stərilən diqqət və qayğının digər bir təzah&uuml;r&uuml;</span><span style="box-sizing: border-box; font-size: 14pt;">&nbsp;muxtar respublikada məhkəmə hakimiyyəti orqanlarının hakim korpusunun formalaşdı&shy;rıl&shy;masında m&uuml;şahidə olunmaqdadır. Belə ki, hakimlərin se&ccedil;ilməsinin Avropada ən m&uuml;tərəqqi və şəffaf qaydaları tətbiq edilərək m&uuml;asir standartlara cavab verən yeni kriteriyalar əsasında ke&ccedil;irilən se&ccedil;im turları nəticəsində y&uuml;ksək biliyə və mənəvi keyfiyyətlərə malik Nax&ccedil;ıvan D&ouml;vlət Universitetinin h&uuml;quq fak&uuml;ltəsinin məzunu olan 16 h&uuml;quqş&uuml;nas muxtar respublikada fəaliyyət g&ouml;stərən məhkəmələrə hakim vəzifələrinə təyin edilmişdir. Onu da qeyd edək ki, uğur qazanmış hakim&shy;liyə namizədlərin i&ccedil;ərisində Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəmə&shy;sinin aparatında işləmiş 6 h&uuml;quqş&uuml;nas m&uuml;xtəlif məhkəmə orqanla&shy;rında hakim vəzifələrinə təyin olunmuşdur.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Hazırda muxtar respublikada hakim korpusunun 50%-dən &ccedil;oxunu yeni qaydalarla se&ccedil;ilmiş gənc nəsil hakimlər təşkil edir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Azərbaycan Respublikasının Prezidenti cənab İlham Əliyev və Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisinin Sədri cənab Vasif Talıbov tərəfindən muxtar respublikada fəaliyyət g&ouml;stərən hakimlərə g&ouml;stərilən y&uuml;ksək etimadın nəticəsidir ki, peşəkarlıq və h&uuml;quqi hazırlıq n&uuml;mayiş etdirən 4 hakim Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinə, 5 hakim məhkəmə sədri vəzifəsinə irəli &ccedil;əkilmiş, habelə 1 hakim Məhkəmə H&uuml;quq Şurasının, 1 hakim isə Hakimlərin Se&ccedil;ki Komitəsinin &uuml;zv&uuml; se&ccedil;ilmişdir. Əvvəllər muxtar respublikamızın məhkəmə orqanlarında fəaliyyət g&ouml;stərmiş 3 hakim hazırda Azərbaycan Respublikasının Ali Məhkəməsində, 6 hakim isə &ouml;lkəmizin digər regionlarının m&uuml;xtəlif məhkəmə orqanlarında hakimlik fəaliyyətlərini davam etdirirlər.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">M&uuml;qayisə &uuml;&ccedil;&uuml;n onu da qeyd edək ki, əgər 1992-ci ildə Nax&ccedil;ıvan</span><span style="box-sizing: border-box; font-size: 14pt;">&nbsp;Muxtar Respublikasının Ali Məhkəməsi sədr və m&uuml;avindən başqa, 3 hakim və 11 məhkəmə aparatı iş&ccedil;isindən ibarət olmuşdursa, hazırda ştat cədvəlinə uyğun olaraq hakimlərin sayı 5 dəfə artırılaraq 14 nəfər,&nbsp; məhkəmə aparatı iş&ccedil;ilərinin sayı isə 6 dəfə artırılaraq 71 nəfər olmuş,&nbsp; beynəlxalq təcr&uuml;bəyə uyğun olaraq hər bir hakim &uuml;&ccedil;&uuml;n k&ouml;mək&ccedil;i ştatı m&uuml;əyyən olunmuşdur.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Məhkəmə hakimiyyətinə g&ouml;stərilən diqqət və qayğının digər n&uuml;munəsi Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi hakimlərinin və məhkəmə iş&ccedil;ilərinin əməyinin y&uuml;ksək qiymətləndirilməsi ilə bağlıdır. Belə ki, &ouml;tən d&ouml;vr ərzində Azərbaycan Respublikası Prezidentinin sərəncamları, Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisi Sədrinin m&uuml;vafiq fərmanlarına uyğun&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.2pt;">olaraq</span>&nbsp;Nax&ccedil;ıvan Muxtar Respublikası Ali Məh&shy;kəməsinin hakimləri və d&ouml;vlət qulluq&ccedil;uları fəxri adlar və medallarla təltif edilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">B&uuml;t&uuml;n bunlarla yanaşı, &ouml;tən illər ərzində Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisi Sədrinin təşəbb&uuml;s&uuml; ilə &ldquo;D&ouml;vlət qulluğu haqqında&rdquo; qanuna dəyişikliklər edilərək Nax&ccedil;ıvan Muxtar Respublikasının Ali Məh&shy;kəməsi 3-c&uuml; kateqoriya d&ouml;vlət orqanları sırasından 2-ci kateqoriya d&ouml;vlət orqanları sırasına qaldırılmışdır. Bu isə Ali Məhkəmədə &ccedil;alışan d&ouml;vlət qulluq&ccedil;ularının maddi təmi&shy;natının artması və onlara daha y&uuml;ksək ixtisas dərəcələrinin verilməsi ilə nəticə&shy;lənmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">G&ouml;r&uuml;lm&uuml;ş işlərin nəticəsidir ki, muxtar respublikamızda insan h&uuml;quq və azadlıqlarının daha səmərəli və keyfiyyətli şəkildə təmin olunmasına əlverişli şərait yaranmışdır. Təkcə bir fakta nəzər salmaq kifayətdir ki, &ouml;tən ilin birinci yarısı ilə m&uuml;qаyisədə 2015-ci ilin birinci yarısında muxtar respublikanın şəhər və rayon məhkəmələri tərə&shy;findən bахılmış m&uuml;lki&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">işlərin sayında 30% artım olmuşdur. Bu statistik g&ouml;stərici isə onu</span>&nbsp;deməyə əsas verir ki, əhalinin məhkəmə orqanlarına və ədalət m&uuml;hakiməsinin obyektiv şəkildə həyata ke&ccedil;irilməsinə inamı g&uuml;n ke&ccedil;dikcə daha da artmaqdadır.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Qeyd edək ki, Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi ədalət&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">m&uuml;hakiməsi ilə yanaşı, əhali arasında h&uuml;quqi maarifləndirmə işinin g&uuml;cləndi&shy;ril&shy;məsinə, hakimlərin, məhkəmə iş&ccedil;i&shy;lərinin</span>&nbsp;ixtisaslarının artırılmasına y&ouml;nələn tədbirlər də həyata ke&ccedil;irir. Bu məqsədlə Azərbaycan Respub&shy;lika&shy;sının Prezidenti cənab İlham Əliyevin adı &ccedil;əkilən fərmanlarını və Nax&ccedil;ı&shy;van Muxtar Respublikası Ali Məclisinin Sədri cənab Vasif Talıbovun məhkə&shy;mə orqanlarına &uuml;nvanladığı t&ouml;vsiyələrini fəaliyyətində rəhbər tutan Nax&ccedil;ı&shy;van Muxtar Respublikasının Ali Məhkəməsi 2006-cı ildən bu g&uuml;nədək muxtar respublikanın məhkəmə və h&uuml;quq-m&uuml;hafizə orqanları arasında ilk və yeganə h&uuml;quqi mətbu nəşr olan B&uuml;lletenini nəşr etdirir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Muxtar Respublikamızda məhkəmə hakimiyyəti orqanlarının fəaliyyə&shy;tində informasiya təminatının həyata ke&ccedil;irilməsinin təkmilləşdirilməsi, eləcə də məhkəmələrdə yeni informasiya-komunikasiya texnologiyalarının geniş tətbiqi istiqamətində də m&uuml;h&uuml;m işlər g&ouml;r&uuml;lm&uuml;şd&uuml;r. Belə ki, Nax&ccedil;ıvan Muxtar Respubli&shy;kası Ali Məclisinin Sədri tərəfindən imzalanan 15 iyul 2011-ci il tarixli &ldquo;Nax&shy;&ccedil;ıvan Muxtar Respublikasında d&ouml;vlət orqanlarının elektron xidmətlər g&ouml;s&shy;tərməsinin təşkili haqqında&rdquo; fərmandan irəli gələn vəzifələrin icrası ilə bağlı Ali Məhkə&shy;mədə hər il g&ouml;r&uuml;&shy;ləcək işlərə dair tədbirlər planı təsdiq edilərək icra olunur.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.2pt;">Əhalinin m&uuml;raciət etmək h&uuml;ququnun daha da asanlaşdırılması məqsə&shy;di&shy;lə elektron xidmətlər g&ouml;stərilməsi &uuml;&ccedil;&uuml;n Ali Məhkəmənin internet saytının &ldquo;M&uuml;raciətlər&rdquo; b&ouml;lməsindən istifadə etmək&shy;lə vətəndaşlar &ouml;z ərizə və şikayətlərini istənilən vaxt elektron formada g&ouml;ndərmək imkanına malikdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.2pt;">Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi &ldquo;Elektron məhkəmə&rdquo; informasiya sisteminin yaradılması haqqında&nbsp; Azərbaycan Respublikası Prezidentinin 13 fevral 2014-c&uuml; il tarixli Sərəncamından irəli gələn vəzifələrin icrası istiqamətində də m&uuml;əyyən işlər g&ouml;rm&uuml;şd&uuml;r. Ədalət m&uuml;hakiməsinin daha səmərəli və şəffaf şəkildə həyata ke&ccedil;irilməsi, aşkarlıq və operativliyin təmin edilməsi məqsədilə 2014-c&uuml; ildə məhkəməyə daxil olan işlərin hakimlər arasında bərabər b&ouml;lg&uuml;s&uuml;n&uuml; m&uuml;əyyən edən &ldquo;Məhkəmə idarəetmə sistemi&rdquo; proqram təminatı hazırlanaraq tətbiq olunmağa başlamışdır.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.2pt;">Bundan başqa, Ali Məhkəmənin Azərbaycan və ingilis dillərində fəaliyyət g&ouml;stərən rəsmi internet saytı 2015-ci ildə x&uuml;susi proqramlaşdırma dilində m&uuml;asir standartlar səviyyəsində yenidən hazırlanmış, istifadə&ccedil;ilərin rahatlığını təmin etmək &uuml;&ccedil;&uuml;n mobil cihazların tələblərinə uyğunlaş&shy;dırıl&shy;mış, saytda yayımlanan məlumatlardan istifadəni asanlaşdırmaq məqsədilə vahid axtarış sistemi qurulmuş, sayt Azərbaycan Respublikasının elektron məhkəmə sisteminin vahid portalına inteqrasiya edilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Bu il həm&ccedil;inin Azərbay&shy;can Respublikası H&ouml;kumətinin D&uuml;nya Bankı ilə birgə maliyyələşdirdiyi &ldquo;M&uuml;tərəqqi ədliyyə xidmətləri və m&uuml;asir&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.2pt;">məhkəmə infrastrukturu&rdquo; layihəsi &ccedil;ər&ccedil;ivəsində həmin informasiya sisteminin</span>&nbsp;Nax&ccedil;ıvan Muxtar Respublika&shy;sı Ali Məclisi Sədrinin dəstəyi ilə&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.2pt;">muxtar respublikada fəaliyyət g&ouml;stərən məhkəmələrdə tətbiqini təmin etmək</span><span style="box-sizing: border-box; letter-spacing: -0.1pt;">&nbsp;&uuml;&ccedil;&uuml;n m&ouml;vcud məhkəmələrin inzibati binalarında m&uuml;vafiq</span>&nbsp;infrastrukturun qurul&shy;ması işinə başlanılmış, hazırda bu sahədə işlər davam etdirilmək&shy;dədir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisinin sədri demişdir:&nbsp;<span style="box-sizing: border-box; font-weight: bold;"><em style="box-sizing: border-box;">&ldquo;M&uuml;stəqil &ouml;lkədə h&uuml;quqi islahatların, vətəndaş cəmiyyəti quruculuğunun həyata ke&ccedil;irilməsi, beynəlxalq &ouml;hdəliklərin yerinə yetirilməsi vacib şərtdir&rdquo;</em></span>. Bu t&ouml;vsiyyələri fəaliyyətində rəhbər tutan Ali Məhkəmə beynəlxalq qurumlar və d&ouml;vlət orqanları ilə əlaqələrini, onlarla təcr&uuml;bə m&uuml;badiləsi aparılması işini daimi diqqət mərkəzində saxlayır, hаkimlərin pеşə vərdişlərinin аrtırılmа&shy;sı, onların h&uuml;quqi biliklərinin daha da m&ouml;hkəmlən&shy;dirilməsi istiqamətində bir sıra tədbirlər yerinə yetirir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">&Ouml;tən d&ouml;vr ərzində Nax&ccedil;ıvan Muxtar Respublikasının Ali Məclisi&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">Sədrinin x&uuml;susi diqqət və qayğısı sayəsində Nax&ccedil;ıvan Muxtar Respublikası</span>&nbsp;Ali Məhkəməsinin, ixtisaslaşdırılmış, rayon (şəhər) məhkəmələrinin hakimləri Amerika Birləşmiş Ştatları, Almaniya və T&uuml;rkiyənin ayrı-ayrı&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.1pt;">məhkəmə orqanla&shy;rında ezamiyyətdə olmuş, təcr&uuml;bə m&uuml;badiləsi aparmışlar.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.2pt;">2007-ci ildə Avropa Şurası Baş Katibinin &ouml;lkəmizdəki x&uuml;susi</span><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">&nbsp;n&uuml;mayəndəsi Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsində olmuşdur.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">2011-ci ildə Nax&ccedil;ıvan Muxtar Respublikasının hakimləri &uuml;&ccedil;&uuml;n &ldquo;Avropa İnsan H&uuml;quqları Konvensiyasının tətbiqinin aktual məsələləri&rdquo; m&ouml;vzusunda seminar ke&ccedil;irilmiş, Azərbaycan Respublikasının Avropa İnsan H&uuml;quqları Məhkəməsindəki hakimi Xanlar Hacıyev həmin seminarda iştirak edərək hakimləri maraqlandıran suallara aydınlıq gətirmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.1pt;">2013-c&uuml; ildə Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi, Azərbaycan H&uuml;quqş&uuml;nasları Konfederasiyası, BMT-nin İnsan H&uuml;quqları &uuml;zrə Ali Ko&shy;missarlığı və Almaniya Fede&shy;ral Ədliyyə Nazirliyinin Beynəlxalq H&uuml;quq Əməkdaşlığı Fondunun təşkilat&ccedil;ılığı ilə Nax&ccedil;ıvan şəhərində Nax&ccedil;ıvan Muxtar Respublikasında aparılan məhkəmə-h&uuml;quq islahatlarına həsr olunmuş bey&shy;nəlxalq seminar ke&ccedil;irilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.2pt;">2013 və 2015-ci illərdə isə Nax&ccedil;ıvan şəhərində Azərbaycan Respublikası Ali Məhkəməsi,</span><span style="box-sizing: border-box; font-size: 14pt;">&nbsp;Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi və Almaniya Bey&shy;nəlxalq Əməkdaşlıq Cəmiyyətinin (GİZ) birgə təşkilat&ccedil;ılığı ilə Nax&ccedil;ıvan Muxtar Respublikasında fəaliyyət g&ouml;stərən məhkəmələ&shy;rin hakimləri &uuml;&ccedil;&uuml;n m&uuml;xtəlif h&uuml;quqi m&ouml;vzulara həsr olunmuş seminarlar ke&ccedil;irilmişdir.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Ke&ccedil;irilmiş seminarın nəticəsi olaraq Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinə &uuml;nvanlanmış minnətdarlıq məktublarında seminarların təşkili, ədliyyə sistemində inkişafın əldə olunması, muxtar respublikada&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.2pt;">fəa&shy;liyyət g&ouml;stərən hakimlərin peşə&shy;karlıq səviyyəsi y&uuml;ksək qiymətləndirilmiş,</span>&nbsp;b&uuml;&shy;t&uuml;n bu nailiyyətlərin gərgin əməyin sayəsində əldə olunması x&uuml;susi olaraq vurğulanmışdır. Məktubda Nax&ccedil;ıvan Muxtar Respublikası ilə yaxından tanış olmaq, onun g&ouml;zəl mənzərələrindən və mehriban insanlarından xoş təəss&uuml;ratlar almaq imkanı &uuml;&ccedil;&uuml;n yaradılmış şəraitə və g&ouml;stərilmiş k&ouml;məyə g&ouml;rə muxtar respublika rəhbərliyinə dərin minnətdarlıq bildirilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi Nax&ccedil;ıvan D&ouml;vlət Universiteti ilə əlaqələrini də daimi diqqət mərkəzində saxlayır, h&uuml;quqş&uuml;naslıq ixtisasının tələbələrinin peşəkar h&uuml;quqş&uuml;nas kimi yetişməsində yaxından iştirak edir.&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.2pt;">Belə ki, Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisinin Sədri tərəfindən imzalanan 27 iyul 2015-ci il tarixli &ldquo;Ali və orta ixtisas təhsili m&uuml;əssisələrində ixtisasların m&uuml;vafiq təşkilatlara hamiliyə verilməsi haqqında&rdquo; Sərəncamın&shy;dan irəli gələn vəzifələrin icrası ilə bağlı Ali Məhkəmədə 2015-ci ildə g&ouml;r&uuml;ləcək işlərə dair tədbirlər planı təsdiq edilərək m&uuml;əyyən işlər g&ouml;r&uuml;lm&uuml;şd&uuml;r.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.2pt;">Qeyd edək ki, təkcə son beş ildə, yəni 2010-2015-ci illərdə Nax&ccedil;ıvan D&ouml;vlət Universitetinin h&uuml;quqş&uuml;naslıq ixtisasını bitirən 26 h&uuml;quqş&uuml;nas Ali Məhkəmənin aparatında, 55 h&uuml;quqş&uuml;nas isə muxtar respub&shy;li&shy;kanın ixtisaslaşdırılmış, şəhər və rayon məhkəmələrində m&uuml;vafiq inzibati vəzifələr &uuml;zrə işə qəbul edilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">&Ouml;tən d&ouml;vr ərzində&nbsp;<span style="box-sizing: border-box; letter-spacing: -0.2pt;">Nax&ccedil;ıvan D&ouml;vlət Universitetində h&uuml;quq fak&uuml;ltəsinin tələbələrinin&nbsp;</span>Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin sədri ilə g&ouml;r&uuml;ş&uuml; təşkil edilmiş, tələbələri maraqlandıran suallar cavablandırılmışdır.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Bundan başqa, beynəlxalq və &ouml;lkə miqyaslı əlamət&shy;dar g&uuml;nlərdə Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin kolle&shy;giya sədrləri və hakimlərinin iştirakı ilə Nax&ccedil;ıvan D&ouml;vlət Univer&shy;sitetində h&uuml;quqş&uuml;naslıq ixtisası &uuml;zrə təhsil alan tələbələr &uuml;&ccedil;&uuml;n h&uuml;quqi tədbirlər və konfranslar ke&ccedil;irilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt;">Ali Məhkəmənin nəşri olan B&uuml;lletenin &ouml;tən n&ouml;mrələrində h&uuml;quq elminə marağın daha da artırılması və h&uuml;quqi biliklərin m&ouml;hkəmləndirilməsi məqsədilə Nax&ccedil;ıvan D&ouml;vlət Universitetinin h&uuml;quqş&uuml;naslıq ixtisasında təhsil alan tələbələrin məqalələ&shy;rinə yer verilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.2pt;">Bununla yanaşı, hazırda Ali Məhkəmənin 2 hakimi və 3 d&ouml;vlət qulluq&ccedil;usu Nax&ccedil;ıvan D&ouml;vlət Universitetinin H&uuml;quq fənləri kafedrasında m&uuml;xtəlif h&uuml;quq sahələri &uuml;zrə pedaqoji fəaliyyətlər g&ouml;stərir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.2pt;">Ali Məhkəmədə ke&ccedil;irilən a&ccedil;ıq məhkəmə iclaslarında h&uuml;quqş&uuml;naslıq ixtisasında təhsil alan tələbələrin iştirakı təmin edilir, onların Ali Məhkəmədə, muxtar respublikada fəaliyyət g&ouml;stərən digər məhkəmələrdə istehsalat təcr&uuml;bəsi ke&ccedil;məsinə geniş şərait yaradılır.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14pt; letter-spacing: -0.2pt;">Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin fəaliyyətinin m&uuml;asir tələblər səviyyəsində qurulmasını g&ouml;stərən başqa bir amil də məhkəmədə zəngin h&uuml;quq ədəbiyyatı ilə təchiz olunmuş kitabxananın fəaliyyət g&ouml;stərməsidir. Bununla məhkəmə&shy;də fəaliyyət g&ouml;stərən hakimlər, aparat iş&ccedil;iləri, h&uuml;quqş&uuml;naslıq ixtisasında təhsil alan tələbələr m&uuml;xtəlif sahələrə aid qa&shy;nunvericilik və h&uuml;quq ədəbiyya&shy;tına olan tələbatını &ouml;dəyirlər</span><span style="box-sizing: border-box; font-size: 14pt;">.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 18pt; outline: none !important;"><span style="box-sizing: border-box; font-size: 14pt; outline: none !important;">G&ouml;r&uuml;nd&uuml;y&uuml; kimi həm qanunvericiliyə gətirilən yeniliklər, həm də məhkəmələrin maddi təminat məsələlərinə g&ouml;stərilən diqqət və qayğı, o c&uuml;mlədən hakim&shy;lərin, məhkəmə iş&ccedil;ilərinin iş şəraitinin m&uuml;asir tələblər səviyyəsinə &ccedil;atdırıl&shy;ması Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi tərəfindən ədalət m&uuml;&shy;hakiməsinin həyata ke&ccedil;irilməsi &uuml;zrə vəzifələrinin keyfiyyətlə yerinə yetiril&shy;məsinə, insan h&uuml;quq və azadlıqlarının səmərəli şəkildə qorunmasına xidmət edir. Ş&uuml;bhə yoxdur ki, g&ouml;r&uuml;lən bu işlər muxtar respubli&shy;kada b&uuml;t&uuml;n məhkəmə orqanlarının s&uuml;rətlə inkişaf etdirilməsinə b&ouml;y&uuml;k təkan vermiş və nəticədə muxtar respublikada insan h&uuml;quq və azadlıq&shy;larının daha m&ouml;hkəm təminatı &uuml;&ccedil;&uuml;n əlverişli zəmin yaratmışdır.</span></p>',
                'created_at' => '2022-05-06 05:19:00',
                'updated_at' => '2022-05-06 06:05:43',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Naxçıvan Muxtar Respublikası Ali Məclisi Sədrinin Sərəncamı',
                'slug' => 'naxcivan-muxtar-respublikasi-ali-m-clisi-s-drinin-s-r-ncami',
                'content' => '<p style="box-sizing: border-box; margin: 0px 0px 10px; text-align: center; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-indent: 1cm;"><strong><span style="box-sizing: border-box; font-size: 16pt; line-height: 24.5333px; font-family: \'Times New Roman\', serif;">Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi iş&ccedil;ilərinin təltif edilməsi haqqında Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisi Sədrinin Sərəncamı</span></strong></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; text-align: center; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-indent: 1cm;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-align: justify; text-indent: 1cm; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 13pt; line-height: 24px; font-family: \'Times New Roman\', serif;">&nbsp;Nax&ccedil;ıvan Muxtar Respublikası Konstitusiyasının 5-ci maddəsinin II hissəsinin 21-ci bəndini rəhbər tutaraq&nbsp;<span style="box-sizing: border-box; font-weight: bold;">qərara&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;alıram:</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-align: justify; text-indent: 1cm; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 13pt; line-height: 24px; font-family: \'Times New Roman\', serif;">Nax&ccedil;ıvan Muxtar Respublikasında məhkəmə hakimiyyəti orqanlarında və d&ouml;vlət qulluğunda səmərəli fəaliyyətlərinə g&ouml;rə:</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-align: justify; text-indent: 1cm; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 13pt; line-height: 24px; font-family: \'Times New Roman\', serif;">Quliyev V&uuml;qar Kərim oğluna</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-align: justify; text-indent: 1cm; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 13pt; line-height: 24px; font-family: \'Times New Roman\', serif;">Mirzəyev İlqar Məhərrəm oğluna &ndash;&nbsp;<span style="box-sizing: border-box; font-weight: bold;">&ldquo;Əməkdar h&uuml;quqş&uuml;nas&rdquo;</span>&nbsp;fəxri adı;</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-align: justify; text-indent: 1cm; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 13pt; line-height: 24px; font-family: \'Times New Roman\', serif;">Vəliyev Yunis Əziz oğluna &ndash;&nbsp;<span style="box-sizing: border-box; font-weight: bold;">&ldquo;Əməkdar d&ouml;vlət qulluq&ccedil;usu&rdquo;&nbsp;</span>fəxri adı;</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-align: justify; text-indent: 1cm; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 13pt; line-height: 24px; font-family: \'Times New Roman\', serif;">Seyidova Xasa Seyidəli qızına &ndash;&nbsp;<span style="box-sizing: border-box; font-weight: bold;">&ldquo;Rəşadətli əməyə g&ouml;rə&rdquo;</span>&nbsp;nişanı verilsin.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-align: right;"><span style="box-sizing: border-box; font-weight: bold;"><span style="box-sizing: border-box; font-size: 13pt; line-height: 18.4px; font-family: \'Times New Roman\', serif;">Vasif TALIBOV</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-align: right;"><span style="box-sizing: border-box; font-weight: bold;"><span style="box-sizing: border-box; font-size: 13pt; line-height: 18.4px; font-family: \'Times New Roman\', serif;">Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisinin Sədri</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 15.6px; text-align: right;"><em style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 13pt; line-height: 18.4px; font-family: \'Times New Roman\', serif;">Nax&ccedil;ıvan şəhəri, 2 oktyabr 2015-ci il</span></em></p>',
                'created_at' => '2022-05-06 05:25:00',
                'updated_at' => '2022-05-06 05:58:34',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'NAXÇIVAN MUXTAR RESPUBLİKASI ALİ MƏCLİSİNİN FƏXRİ FƏRMANI',
                'slug' => 'naxcivan-muxtar-respubli-kasi-ali-m-cli-si-ni-n-f-xri-f-rmani',
                'content' => '<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: \'Times New Roman\', serif; text-align: center;"><img class="decree-img" style="box-sizing: border-box; border: 0px; vertical-align: middle; width: 150px; height: 160px;" src="http://alimehkemetest.nakhchivan.az/storage/courts/January2022/gerb.png" alt="" /></p>
<div class="decree-info" style="box-sizing: border-box; color: #333333; font-family: \'Times New Roman\', serif; text-align: center;">
<h1 class="decree-title" style="box-sizing: border-box; font-size: 30px; margin: 30px 0px; line-height: 1.1; font-family: inherit; color: #548dd4;">NAX&Ccedil;IVAN MUXTAR RESPUBLİKASI<br style="box-sizing: border-box;" />ALİ MƏCLİSİNİN</h1>
<h1 class="decree-titles" style="box-sizing: border-box; font-size: 36px; margin: 30px 0px; font-weight: 500; line-height: 1.1; font-family: inherit; color: #ff0000;">FƏXRİ FƏRMANI<br style="box-sizing: border-box;" />№ 48</h1>
<p class="decree-black" style="box-sizing: border-box; margin: 30px 0px; font-size: 20px; font-style: italic;">Nax&ccedil;ıvan Muxtar Respublikasının<br style="box-sizing: border-box;" />Ali Məhkəməsi səmərəli<br style="box-sizing: border-box;" />fəaliyyətinə g&ouml;rə</p>
<p class="decree-blue" style="box-sizing: border-box; margin: 30px 0px; color: #548dd4; font-size: 22px;">NAX&Ccedil;IVAN MUXTAR RESPUBLİKASI<br style="box-sizing: border-box;" />ALİ MƏCLİSİNİN<br style="box-sizing: border-box;" />FƏXRİ FƏRMANI İLƏ TƏLTİF EDİLMİŞDİR</p>
<p class="decree-endblack" style="box-sizing: border-box; margin: 0px 50px 10px 0px; font-size: 20px; text-align: right;">NAX&Ccedil;IVAN MUXTAR RESPUBLİKASI<br style="box-sizing: border-box;" />ALİ MƏCLİSİNİN SƏDRİ: VASİF TALIBOV</p>
<p class="decree-endblack end" style="box-sizing: border-box; margin: 0px 50px 10px 0px; text-align: right;">02 oktyabr 2015-ci il</p>
</div>',
                'created_at' => '2022-05-06 05:26:53',
                'updated_at' => '2022-05-06 05:26:53',
            ),
        ));
        
        
    }
}