<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FromArtisanPagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pages')->delete();
        
        \DB::table('pages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'author_id' => 6,
                'title' => 'Ümumi məlumat',
                'short_description' => '',
                'body' => '<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="font-size: 14pt;"><strong style="box-sizing: border-box;">Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi apellyasiya instansiyası məhkəməsi kimi &ouml;z ərazi yurisdiksiyasına aid edilmiş birinci instansiya məhkəmələri tərəfindən baxılmış işlər &uuml;zrə məhkəmə aktlarından verilmiş apellyasiya şikayətləri və apellyasiya protestləri &uuml;zrə işlərə baxır. Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi m&uuml;lki kollegiyadan, inzibati kollegiyadan, kommersiya kollegiyasından və cinayət kollegiyadan ibarətdir.</strong></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">NAX&Ccedil;IVAN MR ALİ MƏHKƏMƏSİNİN TARİXİ</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi &ouml;lkəmizin məhkəmə orqanları sistemində &ouml;z&uuml;nəməxsus yer tutur. Məhkəmələr və hakimlər haqqında Azərbaycan Respublikasının 1997-ci il 10 iyun tarixli Qanununda Nax&ccedil;ıvan MR Ali Məhkəməsi apellyasiya instansiyası məhkəməsi kimi təsbit edilmişdir. Lakin digər apellyasiya məhkəmələrindən fərqli olaraq, Nax&ccedil;ıvan MR Ali Məhkəməsi Məhkəmələr və hakimlər haqqında Qanunun 52-ci maddəsinə əsasən həm də Nax&ccedil;ıvan Muxtar Respublikasında ali məhkəmə organı funksiyasını yerinə yetirir və bundan irəli gələn Nax&ccedil;ıvan Muxtar Respublikasının Konstitusiyası ilə nəzərdə tutulmuş konstitusiya nəzarəti &uuml;zrə səlahiyyətləri həyata ke&ccedil;irir (Nax&ccedil;ıvan Muxtar Respublikası Konstitusiyasının 16, 44-c&uuml; maddələri).</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi bu g&uuml;nədək uzun tarixi yol ke&ccedil;miş, bu tarix Nax&ccedil;ıvan Muxtar Respublikasının, b&uuml;t&ouml;vl&uuml;kdə Azərbaycanın tarixi ilə sıx bağlı olub, &ouml;lkənin və muxtar respublikanın m&uuml;xtəlif zaman kəsiyində yaşadığı d&ouml;vr&uuml; &ouml;z&uuml;ndə əks etdirmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">İlk dəfə Azərbaycan Demokratik Cumhuriyyəti d&ouml;vr&uuml;ndə (1918-1920) başlanılan məhkəmə orqanları sisteminin yaradılması prosesi milli hakimiyyətin s&uuml;gutu nəticəsində başa &ccedil;atdırılmamış qaldı.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Lakin, Sovet hakimiyyətinin qurulmasından az m&uuml;ddət sonra Azərbaycanda yenidən məhkəmə orqanlarının təşkilinə başlanıldı.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Azərbaycan SSR Mərkəzi İcraiyyə Komitəsinin 1922-ci il 09 dekabr tarixdə ke&ccedil;irilən 2-ci sessiyasında &laquo;Azərbaycan SSR Məhkəmə quruluşu haqqında&raquo; ilk Əsasnamə qəbul edildi.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">1922-ci il 30 dekabr tarixdə SSRİ-nin yaradılması ilə əlaqədar digər d&ouml;vlət strukturlarında olduğu kimi Azərbaycan SSR məhkəmə orqanları sistemində də m&uuml;əyyən dəyişikliklər həyata ke&ccedil;irildi. 1924-c&uuml; il 29 oktyabr tarixdə &laquo;SSRİ m&uuml;ttəfiq respublikalarının məhkəmə quruluşunun əsasları haqqında&raquo; qanun qəbul edildikdən sonra buna uyğun olaraq Azərbaycan SSR MİK &ouml;z&uuml;n&uuml;n 1925-ci il 3 yanvar tarixli qanunu ilə Azərbaycan SSR Yuxarı Məhkəməsini Azərbaycan SSR Ali Məhkəməsinə &ccedil;evirdi və buna m&uuml;vafiq olaraq Nax&ccedil;ıvan MSSR-də fəaliyyət g&ouml;stərən b&ouml;lmə də artıq 3 oktyabr 1925-ci il tarixdən Ali Məhkəmənin Nax&ccedil;ıvan MSSR-də b&ouml;lməsi adlandırıldı.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Ali Məhkəmənin Nax&ccedil;ıvan MSSR-də fəaliyyət g&ouml;stərən b&ouml;lməsi həm onun səlahiyyətlərinə aid edilmiş cinayət və m&uuml;lki işlər &uuml;zrə birinci instansiya məhkəməsi olaraq, həm də əhatə etdiyi ərazidə təşkil olunmuş xalq məhkəmələri &uuml;&ccedil;&uuml;n yuxarı məhkəmə orqanı kimi təxminən 1934-c&uuml; ilin ortalarınadək fəaliyyət g&ouml;stərdi.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Azərbaycan SSR MİK-nin və XKS-nin 23 avqust 1934-c&uuml; il tarixli qərarı ilə 6 iyul 1927-ci il tarixdən etibarən respublikada məhkəmə quruluşu məsələlərini tənzimləyən Əsasnaməyə bir sıra dəyişikliklər edildli. Həmin dəyişikliklərdən biri də Azərbaycan SSR Ali Məhkəməsinin Nax&ccedil;ıvan MSSR-də fəaliyyət g&ouml;stərən b&ouml;lməsinin ləğv edilməsi və onun əvəzinə Nax&ccedil;ıvan MSSR Baş Məhkəməsinin yaradılması idi.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Qeyd olunan tarixdən yaradılan, 1937-ci ildə Azərbaycan SSR-in yeni Konstitusiyasının qəbul edilməsindən sonra Nax&ccedil;ıvan MSSR Ali Məhkəməsi adını daşıyan məhkəmə m&uuml;xtəlif vaxtlarda m&uuml;vafiq qanunvericiliyin dəyişilməsinə baxmayaraq, b&uuml;t&uuml;n sovet d&ouml;vr&uuml; ərzində demək olar ki, ciddi dəyişikliyə uğramadı və ona aid edilmiş işlərə birinci və yuxarı instansiya məhkəməsi qismində baxmaq, həm&ccedil;inin onun fəaliyyəti dairəsində olan məhkəmələr &uuml;zərində məhkəmə nəzarətini həyata ke&ccedil;irmək funksiyalarıni saxladı.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">SSRİ-nin s&uuml;gutundan az m&uuml;ddət əvvəl 1990-cı il 26 iyun tarixdə qəbul edilən &laquo;Azərbaycan SSR-də məhkəmə quruluşu haqqında&raquo; yeni qanun bu sahədə bəzi dəyişkliklərin həyata ke&ccedil;irilməsini nəzərdə tuturdu.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Lakin həmin d&ouml;vrdə SSRİ-də, o c&uuml;mlədən Azərbaycanda cərayan edən hadisələr, ən başlıcası 18 oktyabr 1991-ci ildə Azərbaycanın d&ouml;vlət m&uuml;stəqilliyini əldə etməsi məhkəmə quruluşunun, ədalət m&uuml;hakiməsi qaydalarının daha geniş və k&ouml;kl&uuml; şəkildə dəyişdirilməsini tələb edirdi.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Buna baxmayaraq, digər sahələrdə olduğu kimi, məhkəmə orqanları sistemində də həmin illərdə aparılan dəyişikliklər yetərli deyildi.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Ancaq 1993-c&uuml; ildə xalqın &uuml;mummilli lideri m&ouml;htərəm Heydər Əliyevin hakimiyyətə qayıdışı ilə bu islahatların aparlması &uuml;&ccedil;&uuml;n real şərait yarandı və Prezident H.Əliyevin bilavasitə rəhbərliyi ilə Azərbaycan Respublikasının m&uuml;stəqil, h&uuml;quqi d&ouml;vlət kimi təşəkk&uuml;l tapmasını təmin edə biləcək məhkəmə islahatlarına başlanıldı.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 15.808px;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Bu islahatların b&uuml;n&ouml;vrəsində m&ouml;htərəm Heydər Əliyevin rəhbərliyi ilə hazırlanmış 12 noyabr 1995-ci ildə &uuml;mumxalq səsverməsi yolu ilə qəbul edilmiş m&uuml;stəqil Azərbycan Respublikasının Konstitusiyası və onun əsasında 10 iyun 1997-ci ildə qəbul edilən &laquo;Məhkəmələr və hakimlər haqqında&raquo; Azərbaycan Respublikasının Qanunu dayanır.<img style="box-sizing: border-box; border: 0px; vertical-align: middle; max-width: 100%; height: auto; line-height: 1.3em; float: right; margin: 10px;" src="http://127.0.0.1:8000/storage/pages/May2022/ali_mehkeme_tarixi1.gif" alt="" width="302" height="227" border="0" /></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">&laquo;Məhkəmələr və Hakimlər haqqında&raquo; 10 iyun 1997-ci il tarixli Qanun Azərbaycan Respublikasında &uuml;&ccedil;pilləli məhkəmə sistemini bərqərar etdi və m&uuml;vafiq Məcəllələr, o c&uuml;mlədən Azərbaycan Respublikasının M&uuml;lki-Prosessual, Cinayət-Prosessual Məcəllələri qəbul edildikdən sonra 2000-ci ilin sentyabr ayından bu sistem real olaraq fəaliyyət g&ouml;stərməyə başladı.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Qanuna g&ouml;rə bu &uuml;&ccedil;pilləli sistem daxilində Nax&ccedil;ıvan MR Ali Məhkəməsinin yeri həm birinci instansiya, həm də ikinci-apellyasiya instansiyası məhkəməsi kimi m&uuml;əyyən edildi.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Bu təyinata uyğun olaraq Ali Məhkəmənin tərkibində qanunla onun səlahiyyətlərinə aid edilmiş ağır cinayət işlərinə baxan ağır cinayətlərə dair işlər &uuml;zrə birinci instansiya kollegiyası, muxtar respublikanın ərazisində fəaliyyət g&ouml;stərən rayon (şəhər) məhkəmələrinin cinayət işləri və inzibati xətalara dair materiallar eləcə də m&uuml;lki işlər &uuml;zrə qanuni q&uuml;vvəyə minməmiş qərarlarından verilən apellyasiya şikayətlərinə və protestlərinə apellyasiya məhkəməsi qismində baxan cinayət işləri və inzibati xətalara dair işlər &uuml;zrə, eləcə də m&uuml;lki işlər &uuml;zrə apellyasiya kollegiyaları yaradıldı.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Azərbaycan Respublikası Prezidentinin 17 iyun 1999-cu il tarixli Fərmanına əsasən Nax&ccedil;ıvan MR Ali Məhkəməsinin hakimlərinin sayı 14 nəfər m&uuml;əyyən olundu və 2000-ci ilin sentyabrından 2003-c&uuml; ilin yanvarınadək məhkəmə hakim heyəti ilə tam komplektləşdirildi.&nbsp;</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">2000-ci ilin sentyabrından &ouml;tən d&ouml;vr ərzində bu formada təşkil olunmuş Nax&ccedil;ıvan MR Ali Məhkəməsinin, &uuml;mumiyyətlə Azərbaycanın b&uuml;t&uuml;n məhkəmə orqanlarının fəaliyyəti &uuml;&ccedil;pilləli məhkəmə sisteminin sovet d&ouml;vr&uuml;ndə və 2000-ci ilin sentyabr ayınadək Azərbaycan Respublikasında m&ouml;vcud olan ikipilləli məhkəmə sistemi ilə m&uuml;qayisədə daha m&uuml;tərəqqi məhkəmə quruluşu forması olduğunu s&uuml;but etdi.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Lakin, bir tərəfdən Azərbaycan Respublikasında gedən inkişaf prosesləri və &nbsp;Azərbaycan Respublikasının Avropa ailəsinə, n&uuml;fuzlu beynəlxalq təşkilatlara daha sıx inteqrasiyası, digər tərəfdən Azərbaycan Respublikasının Apellyasiya və İqtisad məhkəmələrinin b&ouml;lgələrdən uzaqda - Bakı şəhərində təşkil olunmasından t&ouml;rəyən &ccedil;ətinliklər məhkəmə quruluşunda dəyişikliklərin edilməsini bir zərurət kimi meydana gətirdi.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Həmin məhkəmələrin b&ouml;lgələrdən &ccedil;ox uzaqda yerləşməsi ilə bağlı yaranan problemlər Nax&ccedil;ıvan Muxtar Respublikasına m&uuml;nasibətdə &ouml;z&uuml;n&uuml; daha qabarıq şəkildə biruzə verirdi.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">&Ccedil;&uuml;nki, birinci instansiya məhkəmələri kimi fəaliyyət g&ouml;stərən Nax&ccedil;ıvan MR Ali Məhkəməsinin ağır cinayətlərə dair işlər &uuml;zrə kollegiyasının, Nax&ccedil;ıvan Muxtar Respublikasının Hərbi Məhkəməsinin və Nax&ccedil;ıvan MR İqtisad Məhkəməsinin qərarlarından verilən protest və şikayətlərə m&uuml;vafiq olaraq Azərbaycan Respublikasının Apellyasiya Məhkəməsində və Azərbaycan Respublikasının İqtisad Məhkəməsində baxılırdı. Nax&ccedil;ıvan Muxtar Respublikasına qarşı Ermənistan tərəfindən tətbiq olunan blokada isə muxtar respublikada yaşayan vətəndaşlarımızın həmin məhkəmələrdə baxılan işlərlə əlaqədar Bakı şəhərinə gedib-gəlmələri &uuml;&ccedil;&uuml;n &ccedil;ox ciddi əngəllər t&ouml;rədirdi.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Azərbaycan Respublikasının 30 dekabr 2005-ci il tarixli Qanunu ilə Məhkəmələr və hakimlər haqqında Qanuna, Azərbaycan Respublikasının bəzi qanunvericilik aktlarına dəyişikliklər və əlavələr edilməsi barədə Azərbaycan Respublikasının 2007-ci il 16 iyun tarixli Qanunu ilə m&uuml;vafiq prosesual qanunvericiliyə əlavə və dəyişikliklərin edilməsi və Azərbaycan Respublikası Prezidenti tərəfindən məhkəmə hakimiyyətinin m&uuml;asirləşdirilməsi məsələlərinə həsr olunmuş 19 yanvar 2006-cı il tarixli Fərmanın verilməsi nəticəsində məhkəmə islahatları n&ouml;vbəti mərhələyə y&uuml;ksəldi və bu mərhələdə Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi də &ccedil;ox ciddi, m&uuml;tərəqqi dəyişikliklərə uğradı.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Prosessual h&uuml;quq normalarının dəyişilməsini nəzərdə tutan 2007-ci il 16 iyun tarixli Qanunun 16 iyul 2009-cu ildə q&uuml;vvəyə minməsilə Nax&ccedil;ıvan Muxtar Respublikasında ayrıca Ağır Cinayətlərə Dair İşlər &uuml;zrə Məhkəmə yaradıldı və bununla əlaqədar Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsinin tərkibində olan Ağır Cinayətlərə Dair İşlər &uuml;zrə I instansiya kollegiyası ləğv olundu. Eyni zamanda Ali Məhkəmədə əvvəldən m&ouml;vcud olan M&uuml;lki işlər &uuml;zrə kollegiyadan və Cinayət işləri və inzibati xətalara dair işlər &uuml;zrə kollegiyadan savayı daha iki struktur - İqtisadi m&uuml;bahisələrə dair işlər &uuml;zrə kollegiya və Hərbi məhkəmələrin işləri &uuml;zrə kollegiya yaradıldı.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">&nbsp;<img style="box-sizing: border-box; border: 0px; vertical-align: middle; max-width: 100%; height: auto; float: left; margin: 10px;" src="http://127.0.0.1:8000/storage/pages/May2022/AliMehkeme1.gif" alt="" border="0" />Yeni kollegiyaların yaradılmasından sonra 2009-cu ilin ilul ayından etibarən artıq Nax&ccedil;ıvan Muxtar Respublikasının Hərbi Məhkəməsinin baxdığı işlər (o c&uuml;mlədən ağır cinayətlərlə bağlı işlər) &uuml;zrə &ccedil;əxarılmış qərarlardan verilən şikayət və protestlərə həm&ccedil;inin Nax&ccedil;ıvan MR İqtisad Məhkəməsinin qərarlarından verilən şikayətlərə m&uuml;vafiq olaraq Hərbi məhkəmələrin işləri &uuml;zrə kollegiyada və İqtisadi m&uuml;bahisələrə dair işlər &uuml;zrə kollegiyada baxılır. Ağır Cinayətlərə dair İşlər &Uuml;zrə Nax&ccedil;ıvan Muxtar Respublikası Məhkəməsinin &ccedil;ıxardığı qərarlardan verilən şikayət və protestlərə isə Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin cinayət işləri və inzibati xətalara dair işlər &uuml;zrə kollegiyasında baxılır.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Bu yeniliklər Ali Məhkəmə tərəfindən işlərə birinci instansiya gaydasında baxılmasını istisna edir və Ali Məhkəmənin sırf apellyasiya instansiyası məhkəməsi kimi fəaliyyət g&ouml;stərməsini nəzərdə tutur.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Bununla yanaşı qanunvericiliyə gətirilən yeniliklər Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin Nax&ccedil;ıvan MR Konstitusiyası ilə təsbit edilən muxtar respublikada konstitusiya nəzarətinin həyata ke&ccedil;irilməsi ilə bağlı funksiyalarına toxunmamışdır.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Məhkəm h&uuml;quq islahatlarının davamı kimi Məhkəmələr və hakimlər haqqında və Məhkəmə-H&uuml;quq Şurası haqqında Azərbaycan Respublikasının qanunlarına dəyişikliklər və əlavələr edilməsi barədə Azərbaycan Respublikasının 22 iyun 2010-cu il tarixli qanununa əsasən Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin kollegiyalarının adları dəyişdirilərək &nbsp;m&uuml;lki kollegiya, inzibati-iqtisadi kollegiya, cinayət kollegiyası və hərbi kollegiya adlandırılmışdır.&nbsp;<span style="box-sizing: border-box;">&nbsp;&ldquo;Məhkəmələr və hakimlər haqqında&rdquo; Azərbaycan Respublikasının Qanununda dəyişiklik edilməsi barədə&nbsp;<span style="box-sizing: border-box;">9 iyul 2019-cu il tarixli&nbsp;</span>Qanunla&nbsp;<span style="box-sizing: border-box;">&nbsp;Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi m&uuml;lki kollegiyadan, kommersiya kollegiyasından, inzibati kollegiyadan və cinayət kollegiyasından ibarət tərkibdə fəaliyyət g&ouml;stərir.</span></span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Muxtar Respublikanın Ali Məhkəməsində &laquo;Məhkəmələr və hakimlər haqqında&raquo; Qanununun 54-c&uuml; maddəsinə əsasən Rəyasət Heyəti fəaliyyət g&ouml;stərir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Rəyasət Heyətinin tərkibinə Ali Məhkəmənin sədri, onun m&uuml;avini və kollegiya sədrləri daxildir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Qanuna &nbsp;g&ouml;rə Rəyasət Heyəti ədalət m&uuml;hakiməsi funksiyasını yerinə yetirmir və qanunla onun səlahiyyətlərinə aid edilmiş məhkəmənin fəaliyyətinin təmin edilməsi ilə bağlı digər məsələləri həll edir, o c&uuml;mlədən hakimləri kollegiyalar &uuml;zrə b&ouml;l&uuml;şd&uuml;r&uuml;r, məhkəmə təcr&uuml;bəsinin &uuml;mumiləşdirilməsi və məhkəmə statistikasının təhlili barədə materiallara baxır, qanunvericilik aktlarının d&uuml;zg&uuml;n tətbiq edilməsi barədə muxtar respublikanın rayon (şəhər) məhkəmələrinə metodiki k&ouml;mək g&ouml;stərir, Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi yanında Elmi-Məsləhət Şurasının əsasnaməsini və tərkibini təsdiq edir və bir sıra başqa məsələləri həll edir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Elmi-Məsləhət Şurasının Əsasnaməsi və tərkibi Ali Məhkəmənin Rəyasət Heyətinin qərarı ilə təsdiq edilmiş və 2004-c&uuml; ildən Şura fəaliyyətə başlamışdır.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Nax&ccedil;ıvan Muxtar Respublikasının digər məhkəmələri kimi, Ali Məhkəmənin də fəaliyyətinin m&uuml;asir tələblər səviyyəsində təşkil olunmasında Nax&ccedil;ıvan Muxtar Respublikasında h&uuml;quq institutlarının inkişafı haqqında Azərbaycan Respublikası Prezidentinin 2 noyabr 2006-cı il tarixli Fərmanının b&ouml;y&uuml;k rolu olmuşdur.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Muxtar respublikada qısa m&uuml;ddət ərzində bu Fərmanın realizə edilməsi təmin olunmuş və artıq 2007-ci ilin noyabr ayının 29-da Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisi Sədrinin iştirakı ilə Ali Məhkəmənin yeni inzibati binası istifadəyə verilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Nax&ccedil;ıvan şəhərinin mərkəzində yerləşən bu g&ouml;rkəmli binada hakimlərin, məhkəmə aparatı iş&ccedil;ilərinin keyfiyyətli və səmərəli fəaliyyət g&ouml;stərməsi &uuml;&ccedil;&uuml;n zəruri şərait y&uuml;ksək səviyyədə təmin edilmişdir.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; outline: none !important;"><span style="box-sizing: border-box; font-family: arial, helvetica, sans-serif; font-size: 14pt;">Bir tərəfdən qanunvericiliyə gətirilən yeniliklər, digər tərəfdən isə məhkəmələrin maddi təminat məsələlərinə g&ouml;stərilən diqqət, o c&uuml;mlədən hakimlərin, məhkəmə personalının iş şəraitinin m&uuml;asir meyarlar səviyyəsinə &ccedil;atdırılması Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi tərəfindən ədalət m&uuml;hakiməsinin həyata ke&ccedil;irilməsi &uuml;zrə vəzifələrinin keyfiyyətlə yerinə yetirilməsinə, insan h&uuml;quq və azadlıglarının səmərəli şəkildə m&uuml;dafiə olunmasına xidmət edir.</span></p>',
                'image' => NULL,
                'slug' => 'about',
                'redirect_to' => 1,
                'external_link' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'status' => 'ACTIVE',
                'created_at' => '2022-05-05 05:01:00',
                'updated_at' => '2022-05-10 05:36:31',
            ),
            1 => 
            array (
                'id' => 2,
                'author_id' => 6,
                'title' => 'Məhkəmənin sədri',
                'short_description' => '',
                'body' => '<h2 style="box-sizing: border-box; font-family: Arial, sans-serif; font-weight: normal; line-height: 15.808px; color: #000000; margin: 0px 0px 8px; font-size: 20.4px; padding: 20px 0px 8px; text-rendering: optimizelegibility;"><strong style="box-sizing: border-box; line-height: 15.808px;"><img style="box-sizing: border-box; border: 0px; vertical-align: middle; max-width: 100%; height: auto; margin: 5px; float: left;" src="http://www.supremecourt.nakhchivan.az/images/news/Sedr%202018.png" alt="Sedr 2018" /></strong></h2>
<p style="box-sizing: border-box; margin: 0px 0px 6pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;"><strong><span style="box-sizing: border-box; font-size: 14pt;">Əliyev Qasım Vəli oğlu</span></strong></p>
<p style="box-sizing: border-box; margin: 0px 0px 6pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px;"><strong style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 10pt; line-height: 15.3333px;"><span style="font-size: 14pt;">&nbsp;<em style="box-sizing: border-box;"><span style="box-sizing: border-box;">Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin sədri&nbsp;</span></em></span><br style="box-sizing: border-box;" /><br style="box-sizing: border-box;" /></span></strong></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;"><span style="font-size: 14pt;"><strong style="box-sizing: border-box;"><span style="box-sizing: border-box;">&nbsp;Doğulduğu il:</span></strong><span style="box-sizing: border-box;">&nbsp;&nbsp;1971</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;"><span style="font-size: 14pt;"><strong style="box-sizing: border-box;"><span style="box-sizing: border-box;">&nbsp;Təhsili:&nbsp;</span></strong><span style="box-sizing: border-box;">1999,&nbsp;Qafqaz Universiteti. H&uuml;quq fak&uuml;ltəsi</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial; text-align: center;"><span style="font-size: 18pt;"><strong style="box-sizing: border-box;"><span style="box-sizing: border-box;">İş təcr&uuml;bəsi:&nbsp;</span></strong></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;"><span style="box-sizing: border-box; font-size: 10pt; line-height: 15.3333px;"><span style="box-sizing: border-box; color: #444444; font-family: \'Helvetica Neue\', \'Lucida Grande\', Helvetica, Arial, Verdana, sans-serif; font-size: 14px;">&nbsp;</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 0.0001pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 10pt; line-height: 20px;">&nbsp;<span style="font-size: 14pt;">1995 &ndash; 1996&nbsp; &nbsp; &nbsp;Şərur Rayon Prokurorluğunda katib</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 0.0001pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 20px;">&nbsp;1996 &ndash; 2003&nbsp; &nbsp; &nbsp;Şərur Rayon Prokurorluğunda dəftərxana m&uuml;diri</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 0.0001pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 20px;">&nbsp;2003 &ndash; 2007&nbsp; &nbsp; &nbsp;Nax&ccedil;ıvan Muxtar Respublikası Sədərək Rayon Məhkəməsinin hakimi</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 0.0001pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 20px;">&nbsp;2007 &ndash; 2008&nbsp; &nbsp; &nbsp;Nax&ccedil;ıvan Muxtar Respublikası Hərbi Məhkəməsinin sədri</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 0.0001pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 20px;">&nbsp;2008 - 2018 &nbsp;&nbsp;&nbsp;&nbsp; Nax&ccedil;ıvan Muxtar Respublikası Hərbi Məhkəməsinin sədri</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 0.0001pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 20px;">&nbsp;2018 h/h &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin sədri</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 0.0001pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 20px;">&nbsp;2018 h/h &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Məhkəmə-H&uuml;quq Şurasının &uuml;zv&uuml;</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 0.0001pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 20px;">&nbsp;2018 - h/h&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Azərbaycan Respublikası &Uuml;mumi Məhkəmə Hakimləri İctimai Birliyinin (Assosiasiyasının) </span><span style="box-sizing: border-box; font-size: 14pt; line-height: 20px;">&nbsp;İdarə Heyətinin &uuml;zv&uuml;</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 7.5pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 11.85pt; background-image: initial; background-position: initial; background-repeat: initial; background-attachment: initial;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 0.0001pt; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; line-height: 20.4px;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 20px;">&nbsp;2018 -h/h&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Azərbaycan Respublikası Məhkəmə Hakimləri Assosiasiyaları İttifaqının İdarə </span><span style="box-sizing: border-box; font-size: 14pt; line-height: 20px;">Heyətinin &uuml;zv&uuml;</span></p>',
                'image' => NULL,
                'slug' => 'college',
                'redirect_to' => 0,
                'external_link' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'status' => 'ACTIVE',
                'created_at' => '2022-05-05 06:26:00',
                'updated_at' => '2022-05-10 05:45:36',
            ),
            2 => 
            array (
                'id' => 3,
                'author_id' => 6,
                'title' => 'Məhkəmə aparatı',
                'short_description' => '',
                'body' => '<p><img src="http://127.0.0.1:8000/storage/pages/May2022/structure.png" alt="" width="1040" height="1271" /></p>',
                'image' => NULL,
                'slug' => 'structure',
                'redirect_to' => 1,
                'external_link' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'status' => 'ACTIVE',
                'created_at' => '2022-05-05 07:37:00',
                'updated_at' => '2022-05-17 15:47:00',
            ),
            3 => 
            array (
                'id' => 6,
                'author_id' => 6,
                'title' => 'Əlaqə',
                'short_description' => '',
            'body' => '<table class="table table-hover" style="caption-side: bottom; border-collapse: collapse; border-spacing: 0px; margin: 0px 0px 20px; padding: 0px; --bs-table-bg: transparent; --bs-table-striped-color: #212529; --bs-table-striped-bg: rgba(0, 0, 0, 0.05); --bs-table-active-color: #212529; --bs-table-active-bg: rgba(0, 0, 0, 0.1); --bs-table-hover-color: #212529; --bs-table-hover-bg: rgba(0, 0, 0, 0.075); width: 1110px; color: #212529; vertical-align: top; border-color: #dee2e6; max-width: 100%; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; height: 336px;">
<thead style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px; vertical-align: bottom;">
<tr style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px;">
<th class="table-title th-font common bg-gradient" style="box-sizing: border-box; text-align: left; border-width: 0px 0px 2px; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: bottom; line-height: 1.42857; font-size: 16px; font-style: italic; background-image: var(--bs-gradient)  !important; height: 63px; width: 580.562px; border-color: initial inherit currentcolor inherit; border-style: initial solid solid solid;" scope="col">M&uuml;raciətləri qəbul edən struktur b&ouml;lmələr</th>
<th class="table-title" style="box-sizing: border-box; text-align: left; border-width: 0px 0px 2px; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: bottom; line-height: 1.42857; font-size: 16px; font-style: italic; height: 63px; width: 232.969px; border-color: initial inherit currentcolor inherit; border-style: initial solid solid solid;" scope="col">Əlaqə &uuml;&ccedil;&uuml;n məsul şəxslər</th>
<th class="table-title common" style="box-sizing: border-box; text-align: left; border-width: 0px 0px 2px; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: bottom; line-height: 1.42857; font-size: 16px; font-style: italic; height: 63px; width: 264.135px; border-color: initial inherit currentcolor inherit; border-style: initial solid solid solid;" scope="col">Əlaqə &uuml;&ccedil;&uuml;n telefon n&ouml;mrələri</th>
</tr>
</thead>
<tbody style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px; vertical-align: inherit;">
<tr style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px;">
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 37px; width: 580.562px; border-color: #dddddd inherit inherit inherit;">Nax&ccedil;ıvan MR Ali Məhkəməsinin Aparatı</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 37px; width: 232.969px; border-color: #dddddd inherit inherit inherit;">Aparat rəhbəri</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 37px; width: 264.135px; border-color: #dddddd inherit inherit inherit;">545-01-55</td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px;">
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 580.562px; border-color: #dddddd inherit inherit inherit;">&Uuml;mumi ş&ouml;bə</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 232.969px; border-color: #dddddd inherit inherit inherit;">Ş&ouml;bə m&uuml;diri</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 264.135px; border-color: #dddddd inherit inherit inherit;">544-61-76</td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px;">
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 580.562px; border-color: #dddddd inherit inherit inherit;">Vətəndaşların qəbulu və məktublara baxılması ş&ouml;bəsi</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 232.969px; border-color: #dddddd inherit inherit inherit;">Ş&ouml;bə m&uuml;diri</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 264.135px; border-color: #dddddd inherit inherit inherit;">544-61-77</td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px;">
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 56px; width: 580.562px; border-color: #dddddd inherit inherit inherit;">Məhkəmə təcr&uuml;bəsinin &uuml;mumiləşdirilməsi və məhkəmənin statistikasının təhlili ş&ouml;bəsi</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 56px; width: 232.969px; border-color: #dddddd inherit inherit inherit;">Ş&ouml;bə m&uuml;diri</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 56px; width: 264.135px; border-color: #dddddd inherit inherit inherit;">544-61-77</td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px;">
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 580.562px; border-color: #dddddd inherit inherit inherit;">Analitik və qanunvericiliyin sistemləşdirilməsi ş&ouml;bəsi</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 232.969px; border-color: #dddddd inherit inherit inherit;">Ş&ouml;bə m&uuml;diri</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 264.135px; border-color: #dddddd inherit inherit inherit;">544-61-76</td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px;">
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 580.562px; border-color: #dddddd inherit inherit inherit;">İcra məmurları ş&ouml;bəsi</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 232.969px; border-color: #dddddd inherit inherit inherit;">Ş&ouml;bə m&uuml;diri</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 264.135px; border-color: #dddddd inherit inherit inherit;">544-61-75</td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px;">
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 580.562px; border-color: #dddddd inherit inherit inherit;">Mətbuat xidməti</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 232.969px; border-color: #dddddd inherit inherit inherit;">baş məsləhət&ccedil;i</td>
<td style="box-sizing: border-box; border-width: 1px 0px; border-style: solid; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; height: 36px; width: 264.135px; border-color: #dddddd inherit inherit inherit;">544-61-75</td>
</tr>
</tbody>
</table>
<div class="alert alert-light w-100 m-auto text-center" style="box-sizing: border-box; padding: 15px; position: relative; border: 1px solid transparent; border-radius: 4px; color: #818182; background-color: #fefefe; width: 1110px; text-align: center; text-shadow: rgba(255, 255, 255, 0.2) 0px 1px 0px; box-shadow: rgba(255, 255, 255, 0.25) 0px 1px 0px inset, rgba(0, 0, 0, 0.05) 0px 1px 2px; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; margin: auto !important auto !important 20px auto !important;" role="alert"><span style="font-size: 12pt;"><a class="alert-link" style="box-sizing: border-box; background-color: transparent; color: #686868; text-decoration-line: none; margin: 0px; padding: 0px; font-weight: bold;" href="file:///C:/Users/Asus/Pictures/AliM%C9%99hk%C9%99m%C9%99Hazirda/contact.html#">&Uuml;nvan:&nbsp;</a>Nax&ccedil;ıvan şəhəri, AZ 7000, Atat&uuml;rk k&uuml;&ccedil;əsi 19</span>
<p style="box-sizing: border-box; margin: 0px; padding: 0px;"><span style="font-size: 12pt;">Telefon: (036) 544-61-77</span></p>
<p style="box-sizing: border-box; margin: 5px 0px 0px; padding: 0px;"><span style="font-size: 12pt;"><a class="alert-link" style="box-sizing: border-box; background-color: transparent; color: #686868; text-decoration-line: none; margin: 0px; padding: 0px; font-weight: bold;">Fax:&nbsp;</a>(036) 550-12-77</span></p>
<p style="box-sizing: border-box; margin: 5px 0px 0px; padding: 0px;"><span style="font-size: 12pt;"><a class="alert-link" style="box-sizing: border-box; background-color: transparent; color: #686868; text-decoration-line: none; margin: 0px; padding: 0px; font-weight: bold;" href="file:///C:/Users/Asus/Pictures/AliM%C9%99hk%C9%99m%C9%99Hazirda/contact.html#">E-mail:&nbsp;</a>alimehkeme@nakhchivan.az</span></p>
</div>',
                'image' => NULL,
                'slug' => 'contact',
                'redirect_to' => 1,
                'external_link' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'status' => 'ACTIVE',
                'created_at' => '2022-05-05 08:38:00',
                'updated_at' => '2022-05-19 08:36:36',
            ),
            4 => 
            array (
                'id' => 7,
                'author_id' => 6,
                'title' => 'Qəbul qrafiki',
                'short_description' => '',
                'body' => '<div class="first-down-title" style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 1.8rem; text-align: center; font-weight: bold; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">
<p style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px;"><span style="font-size: 14pt;">NAX&Ccedil;IVAN MUXTAR RESPUBLİKASI ALİ MƏHKƏMƏSİNDƏ</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px;"><span style="font-size: 14pt;">QƏBULUN TƏŞKİL EDİLMƏSİ HAQQINDA MƏLUMAT</span></p>
</div>
<p class="first-item" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.6rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><span style="font-size: 12pt;">Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi Aparatının Vətəndaşların qəbulu, və məktublara baxılması ş&ouml;bəsinin iş&ccedil;iləri tərəfindən hər iş g&uuml;n&uuml; saat 9.00-dan 18.00-dək məhkəmənin qəbul otağında m&uuml;raciətlər qəbul olunur, eləcə də şəxslərin ilkin qəbulu aparılır, m&uuml;raciət edən şəxslərə şikayət vermə qaydaları, h&uuml;quq və vəzifələri izah olunur.</span></p>
<p class="item-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><span style="font-size: 12pt;">Məhkəmənin sədri və digər vəzifəli şəxslər tərəfindən vətəndaşların qəbulu aşağıdakı qrafik &uuml;zrə həyata ke&ccedil;irilir.</span></p>
<table class="table table-bordered reception_days mt-5" style="caption-side: bottom; border-collapse: collapse; border-spacing: 0px; padding: 0px; --bs-table-bg: transparent; --bs-table-striped-color: #212529; --bs-table-striped-bg: rgba(0, 0, 0, 0.05); --bs-table-active-color: #212529; --bs-table-active-bg: rgba(0, 0, 0, 0.1); --bs-table-hover-color: #212529; --bs-table-hover-bg: rgba(0, 0, 0, 0.075); width: 1378px; color: #212529; vertical-align: top; border: 1px solid #dddddd; max-width: 100%; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">
<thead style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px; vertical-align: bottom;">
<tr style="box-sizing: border-box; border-style: solid; border-width: 1px 0px; margin: 0px; padding: 0px;">
<th style="box-sizing: border-box; text-align: left; border-width: 0px 1px 2px; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: bottom; border-image: initial; line-height: 1.42857; width: 25px; border-color: initial #dddddd currentcolor #dddddd; border-style: initial solid solid solid;" scope="col">&nbsp;</th>
<th style="box-sizing: border-box; text-align: left; border-width: 0px 1px 2px; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: bottom; border-image: initial; line-height: 1.42857; width: 339px; border-color: initial #dddddd currentcolor #dddddd; border-style: initial solid solid solid;" scope="col"><span style="font-size: 12pt;">Vətəndaşı qəbul etməli olan şəxsin vəzifəsi</span></th>
<th style="box-sizing: border-box; text-align: left; border-width: 0px 1px 2px; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: bottom; border-image: initial; line-height: 1.42857; width: 272px; border-color: initial #dddddd currentcolor #dddddd; border-style: initial solid solid solid;" scope="col"><span style="font-size: 12pt;">Vəzifəli şəxsin soyadı, adı və atasının adı</span></th>
<th style="box-sizing: border-box; text-align: left; border-width: 0px 1px 2px; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: bottom; border-image: initial; line-height: 1.42857; width: 317px;"><span style="font-size: 12pt;">&nbsp;</span></th>
<th style="box-sizing: border-box; text-align: left; border-width: 0px 1px 2px; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: bottom; border-image: initial; line-height: 1.42857; width: 317px; border-color: initial #dddddd currentcolor #dddddd; border-style: initial solid solid solid;" scope="col"><span style="font-size: 12pt;">Qəbul g&uuml;nləri</span></th>
<th style="box-sizing: border-box; text-align: left; border-width: 0px 1px 2px; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: bottom; border-image: initial; line-height: 1.42857; width: 108px; border-color: initial #dddddd currentcolor #dddddd; border-style: initial solid solid solid;" scope="col"><span style="font-size: 12pt;">Qəbul saatı</span></th>
</tr>
</thead>
<tbody style="box-sizing: border-box; border-style: solid; border-width: 0px; margin: 0px; padding: 0px; vertical-align: inherit;">
<tr style="box-sizing: border-box; border-style: solid; border-width: 1px 0px; margin: 0px; padding: 0px;">
<th style="box-sizing: border-box; text-align: left; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; width: 25px;" scope="row"><span style="font-size: 12pt;">1</span></th>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 339px;"><span style="font-size: 12pt;">Nax&ccedil;ıvan MR Ali Məhkəməsinin sədri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 272px;"><span style="font-size: 12pt;">Əliyev Qasım Vəli oğlu</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;">&nbsp;</td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;"><span style="font-size: 12pt;">Hər ayın I və III həftəsinin beşinci g&uuml;nləri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 108px;"><span style="font-size: 12pt;">10:00-12:00</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="font-size: 12pt;">16:00-18:00</span></td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 1px 0px; margin: 0px; padding: 0px;">
<th style="box-sizing: border-box; text-align: left; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; width: 25px;" scope="row"><span style="font-size: 12pt;">2</span></th>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 339px;"><span style="font-size: 12pt;">Nax&ccedil;ıvan MR Ali Məhkəməsinin sədr m&uuml;avini</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 272px;"><span style="font-size: 12pt;">Novruzov Əsgər Novruz oğlu</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;">&nbsp;</td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;"><span style="font-size: 12pt;">Hər ayın II və IV həftəsinin beşinci g&uuml;nləri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 108px;"><span style="font-size: 12pt;">10:00-12:00</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="font-size: 12pt;">16:00-18:00</span></td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 1px 0px; margin: 0px; padding: 0px;">
<th style="box-sizing: border-box; text-align: left; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; width: 25px;" scope="row"><span style="font-size: 12pt;">2</span></th>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 339px;"><span style="font-size: 12pt;">M&uuml;lki kollegiyanın sədri vəzifəsini icra edən</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 272px;"><span style="font-size: 12pt;">Allahverdiyev Əli Kərim oğlu</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;">&nbsp;</td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;"><span style="font-size: 12pt;">iş g&uuml;nləri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 108px;"><span style="font-size: 12pt;">09:00-11:00</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="font-size: 12pt;">16:00-18:00</span></td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 1px 0px; margin: 0px; padding: 0px;">
<th style="box-sizing: border-box; text-align: left; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; width: 25px;" scope="row"><span style="font-size: 12pt;">3</span></th>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 339px;"><span style="font-size: 12pt;">İnzibati kollegiyanın sədri vəzifəsini icra edən</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 272px;"><span style="font-size: 12pt;">Qurbanov Yusifəli S&uuml;leyman oğlu</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;">&nbsp;</td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;"><span style="font-size: 12pt;">iş g&uuml;nləri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 108px;"><span style="font-size: 12pt;">09:00-11:00</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="font-size: 12pt;">16:00-18:00</span></td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 1px 0px; margin: 0px; padding: 0px;">
<th style="box-sizing: border-box; text-align: left; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; width: 25px;" scope="row"><span style="font-size: 12pt;">4</span></th>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 339px;"><span style="font-size: 12pt;">Cinayət kollegiyasının sədri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 272px;"><span style="font-size: 12pt;">Mirzəyev İlqar Məhərrəm oğlu</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;">&nbsp;</td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;"><span style="font-size: 12pt;">iş g&uuml;nləri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 108px;"><span style="font-size: 12pt;">09:00-11:00</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="font-size: 12pt;">16:00-18:00</span></td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 1px 0px; margin: 0px; padding: 0px;">
<th style="box-sizing: border-box; text-align: left; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; width: 25px;" scope="row"><span style="font-size: 12pt;">5</span></th>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 339px;"><span style="font-size: 12pt;">Kommersiya kollegiyanın sədri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 272px;"><span style="font-size: 12pt;">Xıdırov Əhliman Mehman oğlu</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;">&nbsp;</td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;"><span style="font-size: 12pt;">iş g&uuml;nləri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 108px;"><span style="font-size: 12pt;">09:00-11:00</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="font-size: 12pt;">16:00-18:00</span></td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 1px 0px; margin: 0px; padding: 0px;">
<th style="box-sizing: border-box; text-align: left; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; width: 25px;" scope="row"><span style="font-size: 12pt;">6</span></th>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 339px;"><span style="font-size: 12pt;">Aparat rəhbəri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 272px;"><span style="font-size: 12pt;">Qaybalıyev V&uuml;sal Rəhim oğlu</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;">&nbsp;</td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;"><span style="font-size: 12pt;">iş g&uuml;nləri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 108px;"><span style="font-size: 12pt;">09:00-11:00</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="font-size: 12pt;">16:00-18:00</span></td>
</tr>
<tr style="box-sizing: border-box; border-style: solid; border-width: 1px 0px; margin: 0px; padding: 0px;">
<th style="box-sizing: border-box; text-align: left; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; width: 25px;" scope="row"><span style="font-size: 12pt;">7</span></th>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 339px;"><span style="font-size: 12pt;">Ş&ouml;bə m&uuml;dirləri</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 272px;"><span style="font-size: 12pt;">Qurbanova G&uuml;lay Əjdər qızı,</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="font-size: 12pt;">Bayramova Cahan Gəray qızı,</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="font-size: 12pt;">Əliyev Oruc Əli oğlu,</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="font-size: 12pt;">Vəliyev Yunis Əziz oğlu.</span></td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;">&nbsp;</td>
<td style="box-sizing: border-box; border: 1px solid #dddddd; padding: 8px; margin: 0px; background-color: var(--bs-table-bg); box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg); vertical-align: top; line-height: 1.42857; font-size: 14px; width: 317px;"><span style="font-size: 12pt;">iş g&uuml;nləri</span></td>
<td style="width: 108px;">&nbsp;</td>
</tr>
</tbody>
</table>',
                'image' => NULL,
                'slug' => 'reception_days',
                'redirect_to' => 1,
                'external_link' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'status' => 'ACTIVE',
                'created_at' => '2022-05-05 08:52:00',
                'updated_at' => '2022-05-19 08:35:21',
            ),
            5 => 
            array (
                'id' => 8,
                'author_id' => 6,
                'title' => 'Naxçıvan MR Ali Məhkəməsinə məktub yazmaq qaydaları',
                'short_description' => '',
                'body' => '<p class="letter-title text-center" style="box-sizing: border-box; margin: 34px 0px; padding: 0px; text-align: center; font-size: 24px; font-weight: normal; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><span style="font-size: 14pt;"><span style="text-align: justify;">NAX&Ccedil;IVAN MUXTAR RESPUBLİKASI ALİ MƏHKƏMƏSİNİN &Uuml;NVANINA ELEKTRON FORMADA M&Uuml;RACİƏT G&Ouml;NDƏRMƏZDƏN ƏVVƏL, XAHİŞ EDİRİK QAYDALARLA TANIŞ OLUN:</span></span></p>
<div class="letter-first text-justify" style="box-sizing: border-box; margin: 0px; padding: 0px; text-align: justify; font-size: 15px; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 12pt;">1.Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin rəsmi internet səhifəsi vasitəsi ilə elektron formada g&ouml;ndərilmiş m&uuml;raciətlər Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin &Uuml;mumi ş&ouml;bəsinə daxil olur və &rdquo;Vətəndaşların m&uuml;raciətləri haqqında&rdquo; Azərbaycan Respublikasının 2015-ci il 30 sentyabr tarixli, 1308-IVQ n&ouml;mrəli Qanununa, habelə Azərbaycan Respublikası Prezidentinin 2016-cı il 23 iyun tarixli, 950 n&ouml;mrəli Fərmanı ilə təsdiq edilmiş &ldquo;D&ouml;vlət və bələdiyyə orqanlarında, d&ouml;vlət və ya bələdiyyə m&uuml;lkiyyətində olan və ya paylarının (səhmlərinin) nəzarət zərfi d&ouml;vlətə və ya bələdiyyəyə məxsus olan h&uuml;quqi şəxslərdə və b&uuml;dcə təşkilatlarında vətəndaşların m&uuml;raciətləri ilə bağlı karg&uuml;zarlığın aparılması Qaydası&rdquo;na uyğun olaraq qeydiyyata alınır və baxılır.</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 12pt;">2.Mətni yazmazdan əvvəl nəzərdə tutulmuş formanın d&uuml;zg&uuml;n cavablandırılması vacibdir.</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 12pt;">3.Mətn m&uuml;tləq yazıldığı dilin əlifbası ilə tərtib olunmalıdır, b&uuml;t&ouml;vl&uuml;kdə b&ouml;y&uuml;k və ya ki&ccedil;ik hərflərlə yazılmamalı, c&uuml;mlələrə b&ouml;l&uuml;nməli, durğu işarələrindən istifadə qaydalarına riayət edilməlidir.</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 12pt;">4.M&uuml;raciət aydın və səlis c&uuml;mlələrlə yazılmalıdır.</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 12pt;">5.M&uuml;raciət edərkən etika qaydaları g&ouml;zlənilməlidir. Nəzakətsiz ifadələr işlədildikdə və ya m&uuml;əllif &ouml;z&uuml; barədə məlumatları dəqiq g&ouml;stərmədikdə m&uuml;raciətə cavab verilmir.</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" /><span style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 12pt;">6.H&ouml;rmətli internet səhifəsi istifadə&ccedil;iləri! B&ouml;y&uuml;k informasiya axınının işlənməsi x&uuml;susiyyətlərini nəzərə alaraq, xahiş edirik bəzi məhdudiyyətlərə h&ouml;rmətlə yanaşasınız:</span>
<ul style="box-sizing: border-box; padding: 0px; margin: 0px;">
<li style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 13px; list-style: circle;"><span style="font-size: 12pt;">Bir mənbədən elektron məlumatın g&ouml;ndərilməsinin vaxtı serverin y&uuml;klənməsindən asılı olaraq 1-5 dəqiqə ilə məhdudlaşır.</span></li>
<li style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 13px; list-style: circle;"><span style="font-size: 12pt;">Elektron m&uuml;raciətin mətni 1500 işarədən &ccedil;ox olmamalıdır.</span></li>
<li style="box-sizing: border-box; margin: 0px; padding: 0px; font-size: 13px; list-style: circle;"><span style="font-size: 12pt;">Elektron m&uuml;raciətdə qoşma fayllar olmamalıdır. Mətni uzun olan məktublar, sənəd surətləri, fotoşəkillər və yol verilən digər əlavələr Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin E-mail: &uuml;nvanına və ya adi po&ccedil;tla bu &uuml;nvana g&ouml;ndərilməlidir:</span></li>
</ul>
</div>
<p class="location" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 16px; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Nax&ccedil;ıvan şəhəri, AZ 7000, Atat&uuml;rk k&uuml;&ccedil;əsi 19, Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi.</p>',
                'image' => NULL,
                'slug' => 'online',
                'redirect_to' => 0,
                'external_link' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'status' => 'ACTIVE',
                'created_at' => '2022-05-05 08:53:00',
                'updated_at' => '2022-05-11 07:52:52',
            ),
        ));
        
        
    }
}