<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FromArtisanNewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('news')->delete();
        
        \DB::table('news')->insert(array (
            0 => 
            array (
                'id' => 1,
                'image' => 'news\\May2022\\EpcWjaPtzjS0dODUcfeH.jpg',
                'title' => 'Muzey günləri çərçivəsində Naxçıvan Muxtar Respublikası Ali Məhkəməsi və ixtisaslaşdırılmış məhkəmələrin kollektivi Milli Dəyərlər Muzeyində olublar.',
                'slug' => 'muzey-gunl-ri-c-rciv-sind-naxcivan-muxtar-respublikasi-ali-m-hk-m-si-v-ixtisaslasdirilmis-m-hk-m-l-rin-kollektivi-milli-d-y-rl-r-muzeyind-olublar',
                'content' => '<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 1cm;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 21.4667px; font-family: \'Times New Roman\', \'serif\';">Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisi Sədrinin 2014-c&uuml; il 19 dekabr tarixli &ldquo;Muzeylərlə əlaqələrin daha da g&uuml;cləndirilməsi haqqında&rdquo; Sərəncamına uyğun olaraq muxtar respublikada d&ouml;vlət orqanları iş&ccedil;ilərinin muzeylərə kollektiv gedişi təmin olunur. Bu tədbirlərin həyata ke&ccedil;irilməsi muzeylərə marağın artmasına, tariximizin, mədəniyyətimizin &ouml;yrənilməsinə və təbliğinə hərtərəfli şərait yaradır.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 1cm;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 21.4667px; font-family: \'Times New Roman\', \'serif\';">&nbsp;&nbsp;&nbsp;&nbsp; Aprelin 30-da Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi və ixtisaslaşdırılmış məhkəmələrin kollektivi Milli Dəyərlər Muzeyində olublar.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 1cm;"><span style="box-sizing: border-box; font-size: 14pt; line-height: 21.4667px; font-family: \'Times New Roman\', \'serif\';">&nbsp;&nbsp;&nbsp;&nbsp; Muzeydə kollektivə məlumat verilib ki, 2019-cu il sentyabrın 23-də istifadəyə verilmiş muzey 1 otaq və 3 ekspozisiya zalından ibarətdir. Hazırda muzeyin fondunda 236 eksponat vardır. Ekspozisiyada Azərbaycan Respublikasının D&ouml;vlət bayrağı, gerbi və D&ouml;vlət himninin mətni, milli geyimlərimiz və qədim mətbəx əşyalarımız, xal&ccedil;alar və milli musiqi alətlərimiz n&uuml;mayiş olunur. Milli sənətkarlıq n&uuml;munələrindən ibarət eksponatlar, muxtar respublikanın tarixi, mədəniyyəti, memarlıq abidələri, adət-ənənələri ilə bağlı &ccedil;ap olunmuş kitab və ensiklopediyalar, turizm potensialının təbliğinə dair bukletlər m&uuml;xtəlif guşələrdə sərgilənir.</span></p>',
                'created_at' => '2022-05-05 08:12:00',
                'updated_at' => '2022-05-05 08:17:35',
            ),
            1 => 
            array (
                'id' => 2,
                'image' => 'news\\May2022\\zjdsMqdjP9LjrmDNV4Jy.jpg',
                'title' => 'Naxçıvan Muxtar Respublikası Ali Məhkəməsində tələbələr üçün “Ailə qanunvericiliyinin aktual məsələləri”nə həsr olunmuş beş günlük təlim başa çatıb.',
                'slug' => 'naxcivan-muxtar-respublikasi-ali-m-hk-m-sind-t-l-b-l-r-ucun-ail-qanunvericiliyinin-aktual-m-s-l-l-ri-n-h-sr-olunmus-bes-gunluk-t-lim-basa-catib',
                'content' => '<p style="box-sizing: border-box; margin: 0cm 0cm 0.0001pt 0px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 35.45pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: border-box; font-size: 14pt; font-family: \'times new roman\', times;">Tələbələrin h&uuml;quqa dair biliklərini daha da təkmilləşdirmək, eləcə də bu sahəyə olan marağını artırmaq məqsədilə ke&ccedil;irilən təlimdə Nax&ccedil;ıvan D&ouml;vlət Univerisitetinin h&uuml;quqş&uuml;naslıq ixtisası &uuml;zrə təhsil alan tələbələri iştirak edib. Əvvəlcə tələbələr məhkəmənin m&uuml;xtəlif strukturlarında iş şəraiti ilə tanış olub onları maraqlandıran suallar cavablandırılıb. Tələbələr Ali Məhkəmədəki kitabxana ilə tanış olub, məhkəməyə daxil olan sənədlərin, cinayət, m&uuml;lki, inzibati və sair işlərin, materialların qeydiyyatı, rəsmiləşdirilməsi, formalaşdırılması, g&ouml;ndərilməsi və vətəndaşların m&uuml;raciətlərinə baxılması qaydaları haqqında onlara ətraflı məlumat verilib.</span></p>
<p style="box-sizing: border-box; margin: 0cm 0cm 0.0001pt 0px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 35.45pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: border-box; font-size: 14pt; font-family: \'times new roman\', times;">N&ouml;vbəti g&uuml;n Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin əməkdaşları tərəfindən tələbələrin ailə qanunvericiliyi barədə nəzəri biliklərinin təkmilləşdirilməsi istiqamətində &ccedil;ıxışlar edilib.</span></p>
<p style="box-sizing: border-box; margin: 0cm 0cm 0.0001pt 0px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 35.45pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: border-box; font-family: \'times new roman\', times;"><span style="box-sizing: border-box; font-size: 14pt;">Ke&ccedil;irilən təlimin n&ouml;vbəti g&uuml;n&uuml;ndə Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin hakimi, kommersiya kollegiyasının sədri Əhliman Xıdırov&nbsp;</span><span style="box-sizing: border-box; font-size: 14pt;">&ldquo;<em style="box-sizing: border-box;">Ailə qanunvericiliyinin aktual məsələləri</em>&rdquo;<span style="box-sizing: border-box;">&nbsp;barədə tələbələrə təlim ke&ccedil;ib,&nbsp;</span></span><span style="box-sizing: border-box; font-size: 14pt;">təlimdə&nbsp;<span style="box-sizing: border-box;">tələbələr ailə qanunvericiliyinin &uuml;mumi xarakteristikası, ailə m&uuml;bahisələri &uuml;zrə işlərə tətbiq olunmalı olan qanunvericilik aktlarının dairəsi, həmin qəbildən işlərə baxılması zamanı formalaşmış vahid məhkəmə təcr&uuml;bəsi barədə məlumatlandırılıb,</span>&nbsp;<span style="box-sizing: border-box;">tələbələri maraqlandıran suallar&nbsp;</span>hakim tərəfindən cavablandırılıb,&nbsp;<span style="box-sizing: border-box;">m&ouml;vzu ətrafında tələbələrin iştirakı ilə qarşılıqlı m&uuml;zakirə aparılıb.</span></span></span></p>
<p style="box-sizing: border-box; margin: 0cm 0cm 0.0001pt 0px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 35.45pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: border-box; font-family: \'times new roman\', times;"><span style="box-sizing: border-box; font-size: 14pt;">Sonrakı g&uuml;n tələbələrin&nbsp;</span><span style="box-sizing: border-box; font-size: 14pt;">ailə qanunvericiliyinin tətbiq dairəsinə daxil olan işlər &uuml;zrə məhkəmə iclaslarında&nbsp;<span style="box-sizing: border-box;">iştirakları təmin olunub.</span></span></span></p>
<p style="box-sizing: border-box; margin: 0cm 0cm 7.5pt 0px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 35.45pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: border-box; font-size: 14pt; font-family: \'times new roman\', times;">Layihənin sonuncu g&uuml;n&uuml; Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin sədri Qasım Əliyev tələbələrlə g&ouml;r&uuml;ş&uuml;b. O, &ouml;lkədə aparılan h&uuml;quqi islahatların tərkib hissəsi kimi məhkəmə orqanlarında &ccedil;alışacaq y&uuml;ksək peşəkarlığa malik, layiqli və humanist kadrların formalaşdırılmasının vacibliyini vurğulayıb. Qasım Əliyev Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisi Sədrinin m&uuml;vafiq sərəncamlarının gələcəyin fəal, təşəbb&uuml;skar, vətənpərvər ruhlu kadrlarının yetişdirilməsi istiqamətində atılmış əhəmiyyətli addımlardan biri olduğunu bildirib, həyata ke&ccedil;irilən tədbirlərin gələcəkdə də davam etdiriləcəyini diqqətə &ccedil;atdırıb.</span></p>
<p style="box-sizing: border-box; margin: 0cm 0cm 7.5pt 0px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 35.45pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="box-sizing: border-box; font-size: 14pt; font-family: \'times new roman\', times;"><img style="box-sizing: border-box; border: 0px; vertical-align: middle; max-width: 100%; height: auto; margin: 5px; float: right;" src="http://www.supremecourt.nakhchivan.az/images/news/29.04.2022%20(3).jpg" alt="29.04.2022 (3)" width="250" height="167" />Tədbirdə &ccedil;ıxış edən kommersiya kollegiyasının sədri Əhliman Xıdırov bildirib ki, Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisi Sədrinin m&uuml;vafiq sərəncamlarının icrası &ccedil;ər&ccedil;ivəsində Nax&ccedil;ıvan D&ouml;vlət Universiteti ilə Ali Məhkəmə arasında qarşılıqlı əməkdaşlıq qurulub və bu istiqamətdə həyata ke&ccedil;irilən belə tədbirlərin təşkili gələcəkdə m&uuml;vafiq sahələrdə &ccedil;alışacaq kadrların daha peşəkar yetişməsinə, ixtisaslarına dərindən yiyələnmələrinə yeni imkanlar yaradır.</span></p>
<p style="box-sizing: border-box; margin: 0cm 0cm 7.5pt 0px; color: #000000; font-family: Arial, sans-serif; font-size: 13.6px; text-align: justify; text-indent: 35.45pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; outline: none !important;"><span style="box-sizing: border-box; font-size: 14pt; font-family: \'times new roman\', times;">Universitetin Beynəlxalq m&uuml;nasibətlər və h&uuml;quq fak&uuml;ltəsinin dekan m&uuml;avini Abbas Əhmədov &ccedil;ıxış edərək Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisi Sədrinin m&uuml;vafiq sərəncamlarına uyğun olaraq Ali Məhkəmə ilə qarşılıqlı əməkdaşlıq &ccedil;ər&ccedil;ivəsində ke&ccedil;irilməsi ənənəvi hal almış bu c&uuml;r tədbirlərin tələbələrin peşəkar kadrlar kimi yetişdirilməsində m&uuml;h&uuml;m əhəmiyyətini vurğulayaraq yaradılmış şəraitə g&ouml;rə minnətdarlığını bildirib.</span></p>',
                'created_at' => '2022-05-05 13:35:28',
                'updated_at' => '2022-05-05 13:35:28',
            ),
        ));
        
        
    }
}