<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FromArtisanMenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-04-27 18:17:11',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-04-27 18:17:11',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-04-27 18:17:11',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-04-27 18:17:11',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-04-27 18:17:11',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 10,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-04-27 18:17:11',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 11,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-04-27 18:17:11',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 12,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-04-27 18:17:11',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 13,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-04-27 18:17:11',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-04-27 18:17:11',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 2,
                'title' => 'Əsas səhİfə',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-home',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2022-04-27 19:39:33',
                'updated_at' => '2022-04-27 20:06:45',
                'route' => 'home',
                'parameters' => 'null',
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 2,
                'title' => 'Məhkəmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2022-04-27 19:43:05',
                'updated_at' => '2022-04-27 19:43:05',
                'route' => NULL,
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 2,
                'title' => 'Hüquqİ aktlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2022-04-27 19:43:32',
                'updated_at' => '2022-04-27 20:05:49',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 2,
                'title' => 'Məhkəmə sənədlərİ',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2022-04-27 19:43:48',
                'updated_at' => '2022-04-27 20:06:02',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 2,
                'title' => 'Mətbuat xidmətİ',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 19,
                'created_at' => '2022-04-27 19:44:10',
                'updated_at' => '2022-04-27 20:06:11',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 2,
                'title' => 'Hüquqİ maarİfləndİrmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 20,
                'created_at' => '2022-04-27 19:44:24',
                'updated_at' => '2022-04-27 20:06:26',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 3,
                'title' => 'home',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-04-28 05:33:40',
                'updated_at' => '2022-04-29 07:36:26',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 3,
                'title' => 'Məhkəmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-04-28 05:52:27',
                'updated_at' => '2022-04-28 07:34:00',
                'route' => 'court',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 3,
                'title' => 'Hüquqİ aktlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-04-28 05:52:47',
                'updated_at' => '2022-04-28 07:45:23',
                'route' => NULL,
                'parameters' => 'null',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 3,
                'title' => 'Ümumi məlumat',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 1,
                'created_at' => '2022-04-28 05:53:07',
                'updated_at' => '2022-04-29 13:20:23',
                'route' => '\\about',
                'parameters' => 'null',
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 3,
                'title' => 'Məhkəmənin sədri',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 2,
                'created_at' => '2022-04-28 05:53:22',
                'updated_at' => '2022-05-05 07:15:13',
                'route' => '\\college',
                'parameters' => 'null',
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 3,
                'title' => 'Rəyasət heyəti',
                'url' => '',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 3,
                'created_at' => '2022-04-28 05:53:33',
                'updated_at' => '2022-05-05 07:42:09',
                'route' => 'https://courts.gov.az/az/nakhchivansupreme/board/Ryast-Heyti_5',
                'parameters' => 'null',
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 3,
                'title' => 'Hakimlər',
                'url' => '',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 4,
                'created_at' => '2022-04-28 07:36:58',
                'updated_at' => '2022-04-28 07:41:33',
                'route' => 'https://courts.gov.az/az/nakhchivansupreme/judges',
                'parameters' => 'null',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 3,
                'title' => 'Məhkəmənin strukturu',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 5,
                'created_at' => '2022-04-28 07:37:24',
                'updated_at' => '2022-05-05 07:38:18',
                'route' => '\\structure',
                'parameters' => 'null',
            ),
            24 => 
            array (
                'id' => 25,
                'menu_id' => 3,
                'title' => 'Məhkəmə aparatı',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 6,
                'created_at' => '2022-04-28 07:42:28',
                'updated_at' => '2022-04-28 07:42:34',
                'route' => NULL,
                'parameters' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'menu_id' => 3,
                'title' => 'Ali Məhkəmə - 90',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 7,
                'created_at' => '2022-04-28 07:42:59',
                'updated_at' => '2022-04-28 07:43:12',
                'route' => NULL,
                'parameters' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'menu_id' => 3,
                'title' => 'Azərbaycan Respublikasının hüquqi aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 19,
                'order' => 1,
                'created_at' => '2022-04-28 07:46:23',
                'updated_at' => '2022-05-05 12:57:15',
                'route' => '\\legalact',
                'parameters' => 'null',
            ),
            27 => 
            array (
                'id' => 28,
                'menu_id' => 3,
                'title' => 'Naxçıvan Muxtar Respublikasının hüquqi aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 19,
                'order' => 2,
                'created_at' => '2022-04-28 07:47:35',
                'updated_at' => '2022-04-28 07:48:51',
                'route' => 'http://huquqiaktlar.nakhchivan.az/Akts.aspx',
                'parameters' => 'null',
            ),
            28 => 
            array (
                'id' => 29,
                'menu_id' => 3,
                'title' => 'Beynəlxalq hüquqi sənədlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 19,
                'order' => 3,
                'created_at' => '2022-04-28 07:48:07',
                'updated_at' => '2022-05-05 12:44:10',
                'route' => '\\internationaldocument',
                'parameters' => 'null',
            ),
            29 => 
            array (
                'id' => 30,
                'menu_id' => 3,
                'title' => 'Məhkəmə sənədlərİ',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-04-28 07:49:32',
                'updated_at' => '2022-04-28 07:54:07',
                'route' => NULL,
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => 31,
                'menu_id' => 3,
                'title' => 'Rəyasət heyətinin qərarları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 30,
                'order' => 1,
                'created_at' => '2022-04-28 07:50:03',
                'updated_at' => '2022-05-05 13:23:59',
                'route' => '\\decisionpresidia',
                'parameters' => 'null',
            ),
            31 => 
            array (
                'id' => 32,
                'menu_id' => 3,
                'title' => 'Məhkəmə aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 30,
                'order' => 2,
                'created_at' => '2022-04-28 07:50:32',
                'updated_at' => '2022-04-28 07:51:21',
                'route' => 'https://e-mehkeme.gov.az/Public/Anonymizedecisions?courtid=113',
                'parameters' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'menu_id' => 3,
                'title' => 'Avropa İnsan hüquqları məhkəməsinin qərarları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 30,
                'order' => 3,
                'created_at' => '2022-04-28 07:51:10',
                'updated_at' => '2022-04-28 07:51:22',
                'route' => 'https://hudoc.echr.coe.int/eng#{%22documentcollectionid2%22:[%22GRANDCHAMBER%22,%22CHAMBER%22]}',
                'parameters' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'menu_id' => 3,
                'title' => 'Mətbuat xİdmətİ',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-04-28 07:53:32',
                'updated_at' => '2022-04-28 07:54:11',
                'route' => NULL,
                'parameters' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'menu_id' => 3,
                'title' => 'Xəbərlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 1,
                'created_at' => '2022-04-28 07:53:55',
                'updated_at' => '2022-05-05 07:29:06',
                'route' => '/news',
                'parameters' => 'null',
            ),
            35 => 
            array (
                'id' => 36,
                'menu_id' => 3,
                'title' => 'Hesabatlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 2,
                'created_at' => '2022-04-28 07:54:23',
                'updated_at' => '2022-04-28 07:55:00',
                'route' => NULL,
                'parameters' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'menu_id' => 3,
                'title' => 'Çıxışlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 3,
                'created_at' => '2022-04-28 07:54:49',
                'updated_at' => '2022-05-05 13:38:41',
                'route' => '\\speech',
                'parameters' => 'null',
            ),
            37 => 
            array (
                'id' => 38,
                'menu_id' => 3,
                'title' => 'Foto materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 4,
                'created_at' => '2022-04-28 07:55:18',
                'updated_at' => '2022-04-28 07:55:51',
                'route' => NULL,
                'parameters' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'menu_id' => 3,
                'title' => 'Video materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 5,
                'created_at' => '2022-04-28 07:55:33',
                'updated_at' => '2022-04-28 07:55:55',
                'route' => NULL,
                'parameters' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'menu_id' => 3,
                'title' => 'Məqalələr',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 6,
                'created_at' => '2022-04-28 07:55:47',
                'updated_at' => '2022-04-28 07:55:57',
                'route' => NULL,
                'parameters' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'menu_id' => 3,
                'title' => 'Hüquqİ Maarİfləndİrmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2022-04-28 07:56:29',
                'updated_at' => '2022-04-28 07:57:40',
                'route' => NULL,
                'parameters' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'menu_id' => 3,
                'title' => 'Sual-cavab',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 41,
                'order' => 1,
                'created_at' => '2022-04-28 07:57:05',
                'updated_at' => '2022-05-05 12:29:20',
                'route' => '\\faq',
                'parameters' => 'null',
            ),
            42 => 
            array (
                'id' => 43,
                'menu_id' => 3,
                'title' => 'Maarifləndirici materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 41,
                'order' => 2,
                'created_at' => '2022-04-28 07:57:22',
                'updated_at' => '2022-04-28 07:59:05',
                'route' => NULL,
                'parameters' => '',
            ),
            43 => 
            array (
                'id' => 44,
                'menu_id' => 3,
                'title' => 'Tədbirlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 41,
                'order' => 3,
                'created_at' => '2022-04-28 07:57:36',
                'updated_at' => '2022-04-28 07:58:48',
                'route' => NULL,
                'parameters' => '',
            ),
            44 => 
            array (
                'id' => 46,
                'menu_id' => 4,
                'title' => 'Məhkəmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-04-28 08:11:26',
                'updated_at' => '2022-04-28 08:37:15',
                'route' => NULL,
                'parameters' => 'null',
            ),
            45 => 
            array (
                'id' => 47,
                'menu_id' => 4,
                'title' => 'Məhkəmənin sədri',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 2,
                'created_at' => '2022-04-28 08:34:40',
                'updated_at' => '2022-04-28 10:01:15',
                'route' => NULL,
                'parameters' => 'null',
            ),
            46 => 
            array (
                'id' => 48,
                'menu_id' => 4,
                'title' => 'Hüquqi aktlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-04-28 08:34:56',
                'updated_at' => '2022-04-28 10:02:32',
                'route' => NULL,
                'parameters' => 'null',
            ),
            47 => 
            array (
                'id' => 49,
                'menu_id' => 4,
                'title' => 'Mətbuat xidməti',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-04-28 08:35:14',
                'updated_at' => '2022-04-28 10:15:32',
                'route' => NULL,
                'parameters' => NULL,
            ),
            48 => 
            array (
                'id' => 51,
                'menu_id' => 4,
                'title' => 'Ümumi məlumat',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 1,
                'created_at' => '2022-04-28 08:36:02',
                'updated_at' => '2022-04-28 08:37:19',
                'route' => NULL,
                'parameters' => NULL,
            ),
            49 => 
            array (
                'id' => 52,
                'menu_id' => 4,
                'title' => 'Rəyasət heyəti',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 3,
                'created_at' => '2022-04-28 10:01:40',
                'updated_at' => '2022-04-28 10:01:50',
                'route' => NULL,
                'parameters' => NULL,
            ),
            50 => 
            array (
                'id' => 53,
                'menu_id' => 4,
                'title' => 'Məhkəmə sənədləri',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-04-28 10:02:50',
                'updated_at' => '2022-04-28 10:15:32',
                'route' => NULL,
                'parameters' => NULL,
            ),
            51 => 
            array (
                'id' => 55,
                'menu_id' => 4,
                'title' => 'Hüquqi maarifləndirmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-04-28 10:03:36',
                'updated_at' => '2022-04-28 10:20:35',
                'route' => NULL,
                'parameters' => NULL,
            ),
            52 => 
            array (
                'id' => 56,
                'menu_id' => 4,
                'title' => 'Hakimlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 4,
                'created_at' => '2022-04-28 10:04:07',
                'updated_at' => '2022-04-28 10:05:35',
                'route' => NULL,
                'parameters' => NULL,
            ),
            53 => 
            array (
                'id' => 57,
                'menu_id' => 4,
                'title' => 'Məhkəmənin strukturu',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 5,
                'created_at' => '2022-04-28 10:04:25',
                'updated_at' => '2022-04-28 10:05:42',
                'route' => NULL,
                'parameters' => NULL,
            ),
            54 => 
            array (
                'id' => 58,
                'menu_id' => 4,
                'title' => 'Məhkəmə aparatı',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 6,
                'created_at' => '2022-04-28 10:04:50',
                'updated_at' => '2022-04-28 10:05:53',
                'route' => NULL,
                'parameters' => NULL,
            ),
            55 => 
            array (
                'id' => 59,
                'menu_id' => 4,
                'title' => 'Ali məhkəmə - 90',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 7,
                'created_at' => '2022-04-28 10:05:17',
                'updated_at' => '2022-04-28 10:05:57',
                'route' => NULL,
                'parameters' => NULL,
            ),
            56 => 
            array (
                'id' => 60,
                'menu_id' => 4,
                'title' => 'Azərbaycan Respublikasının hüquqi aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 48,
                'order' => 1,
                'created_at' => '2022-04-28 10:14:32',
                'updated_at' => '2022-04-28 10:15:16',
                'route' => NULL,
                'parameters' => NULL,
            ),
            57 => 
            array (
                'id' => 61,
                'menu_id' => 4,
                'title' => 'Naxçıvan Muxtar Respublikasının hüquqi aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 48,
                'order' => 2,
                'created_at' => '2022-04-28 10:14:47',
                'updated_at' => '2022-04-28 10:15:21',
                'route' => NULL,
                'parameters' => NULL,
            ),
            58 => 
            array (
                'id' => 62,
                'menu_id' => 4,
                'title' => 'Beynəlxalq hüquqi sənədlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 48,
                'order' => 3,
                'created_at' => '2022-04-28 10:15:00',
                'updated_at' => '2022-04-28 10:15:24',
                'route' => NULL,
                'parameters' => NULL,
            ),
            59 => 
            array (
                'id' => 63,
                'menu_id' => 4,
                'title' => 'Rəyasət heyətinin qərarları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 53,
                'order' => 1,
                'created_at' => '2022-04-28 10:15:56',
                'updated_at' => '2022-04-28 10:16:32',
                'route' => NULL,
                'parameters' => NULL,
            ),
            60 => 
            array (
                'id' => 64,
                'menu_id' => 4,
                'title' => 'Məhkəmə aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 53,
                'order' => 2,
                'created_at' => '2022-04-28 10:16:09',
                'updated_at' => '2022-04-28 10:16:39',
                'route' => NULL,
                'parameters' => NULL,
            ),
            61 => 
            array (
                'id' => 65,
                'menu_id' => 4,
                'title' => 'Avropa İnsan Hüquqları Məhkəməsinin qərarları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 53,
                'order' => 3,
                'created_at' => '2022-04-28 10:16:23',
                'updated_at' => '2022-04-28 10:16:49',
                'route' => NULL,
                'parameters' => NULL,
            ),
            62 => 
            array (
                'id' => 66,
                'menu_id' => 4,
                'title' => 'Xəbərlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 1,
                'created_at' => '2022-04-28 10:17:06',
                'updated_at' => '2022-04-28 10:18:41',
                'route' => NULL,
                'parameters' => NULL,
            ),
            63 => 
            array (
                'id' => 67,
                'menu_id' => 4,
                'title' => 'Hesabatlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 2,
                'created_at' => '2022-04-28 10:17:17',
                'updated_at' => '2022-04-28 10:18:45',
                'route' => NULL,
                'parameters' => NULL,
            ),
            64 => 
            array (
                'id' => 68,
                'menu_id' => 4,
                'title' => 'Çıxışlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 3,
                'created_at' => '2022-04-28 10:17:49',
                'updated_at' => '2022-04-28 10:18:52',
                'route' => NULL,
                'parameters' => NULL,
            ),
            65 => 
            array (
                'id' => 69,
                'menu_id' => 4,
                'title' => 'Foto materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 4,
                'created_at' => '2022-04-28 10:18:02',
                'updated_at' => '2022-04-28 10:18:55',
                'route' => NULL,
                'parameters' => NULL,
            ),
            66 => 
            array (
                'id' => 70,
                'menu_id' => 4,
                'title' => 'Video materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 5,
                'created_at' => '2022-04-28 10:18:17',
                'updated_at' => '2022-04-28 10:18:57',
                'route' => NULL,
                'parameters' => NULL,
            ),
            67 => 
            array (
                'id' => 71,
                'menu_id' => 4,
                'title' => 'Məqalələr',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 6,
                'created_at' => '2022-04-28 10:18:34',
                'updated_at' => '2022-04-28 10:19:00',
                'route' => NULL,
                'parameters' => NULL,
            ),
            68 => 
            array (
                'id' => 72,
                'menu_id' => 4,
                'title' => 'Sual-cavab',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 55,
                'order' => 1,
                'created_at' => '2022-04-28 10:19:51',
                'updated_at' => '2022-04-28 10:20:35',
                'route' => NULL,
                'parameters' => NULL,
            ),
            69 => 
            array (
                'id' => 73,
                'menu_id' => 4,
                'title' => 'Maarifləndirici materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 55,
                'order' => 2,
                'created_at' => '2022-04-28 10:20:06',
                'updated_at' => '2022-04-28 10:20:37',
                'route' => NULL,
                'parameters' => NULL,
            ),
            70 => 
            array (
                'id' => 74,
                'menu_id' => 4,
                'title' => 'Tədbirlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 55,
                'order' => 3,
                'created_at' => '2022-04-28 10:20:22',
                'updated_at' => '2022-04-28 10:20:44',
                'route' => NULL,
                'parameters' => NULL,
            ),
            71 => 
            array (
                'id' => 75,
                'menu_id' => 5,
                'title' => 'youtube',
                'url' => 'https://www.youtube.com/',
                'target' => '_blank',
                'icon_class' => 'fa-youtube',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 21,
                'created_at' => '2022-04-28 10:26:44',
                'updated_at' => '2022-04-28 10:42:04',
                'route' => NULL,
                'parameters' => '',
            ),
            72 => 
            array (
                'id' => 76,
                'menu_id' => 5,
                'title' => 'facebook',
                'url' => 'https://www.facebook.com/',
                'target' => '_blank',
                'icon_class' => 'fa-facebook-f',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 22,
                'created_at' => '2022-04-28 10:27:42',
                'updated_at' => '2022-04-28 10:51:57',
                'route' => NULL,
                'parameters' => '',
            ),
            73 => 
            array (
                'id' => 77,
                'menu_id' => 5,
                'title' => 'twitter',
                'url' => 'https://twitter.com/?lang=tr',
                'target' => '_blank',
                'icon_class' => 'fa-twitter',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 23,
                'created_at' => '2022-04-28 10:28:28',
                'updated_at' => '2022-04-28 10:42:21',
                'route' => NULL,
                'parameters' => '',
            ),
            74 => 
            array (
                'id' => 78,
                'menu_id' => 5,
                'title' => 'instagram',
                'url' => 'https://www.instagram.com/',
                'target' => '_blank',
                'icon_class' => 'fa-instagram',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 24,
                'created_at' => '2022-04-28 10:28:54',
                'updated_at' => '2022-04-28 10:42:37',
                'route' => NULL,
                'parameters' => '',
            ),
            75 => 
            array (
                'id' => 79,
                'menu_id' => 5,
                'title' => 'telegram',
                'url' => 'https://telegram.org/',
                'target' => '_blank',
                'icon_class' => 'fa-telegram',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 25,
                'created_at' => '2022-04-28 10:29:38',
                'updated_at' => '2022-04-28 10:42:52',
                'route' => NULL,
                'parameters' => '',
            ),
            76 => 
            array (
                'id' => 80,
                'menu_id' => 1,
                'title' => 'Languages',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 26,
                'created_at' => '2022-04-28 12:04:31',
                'updated_at' => '2022-04-28 12:04:31',
                'route' => 'voyager.languages.index',
                'parameters' => NULL,
            ),
            77 => 
            array (
                'id' => 81,
                'menu_id' => 1,
                'title' => 'News',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 27,
                'created_at' => '2022-04-28 12:40:21',
                'updated_at' => '2022-04-28 12:40:21',
                'route' => 'voyager.news.index',
                'parameters' => NULL,
            ),
            78 => 
            array (
                'id' => 83,
                'menu_id' => 1,
                'title' => 'Contacts',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 28,
                'created_at' => '2022-04-28 18:34:28',
                'updated_at' => '2022-04-28 18:34:28',
                'route' => 'voyager.contacts.index',
                'parameters' => NULL,
            ),
            79 => 
            array (
                'id' => 84,
                'menu_id' => 1,
                'title' => 'Forpeople',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 29,
                'created_at' => '2022-04-29 06:03:24',
                'updated_at' => '2022-04-29 06:03:24',
                'route' => 'voyager.forpersons.index',
                'parameters' => NULL,
            ),
            80 => 
            array (
                'id' => 85,
                'menu_id' => 1,
                'title' => 'Services',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 30,
                'created_at' => '2022-04-29 06:22:54',
                'updated_at' => '2022-04-29 06:22:54',
                'route' => 'voyager.services.index',
                'parameters' => NULL,
            ),
            81 => 
            array (
                'id' => 86,
                'menu_id' => 1,
                'title' => 'Nmrcourts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-treasure',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 31,
                'created_at' => '2022-04-29 07:16:30',
                'updated_at' => '2022-04-29 07:16:30',
                'route' => 'voyager.nmrcourts.index',
                'parameters' => NULL,
            ),
            82 => 
            array (
                'id' => 87,
                'menu_id' => 1,
                'title' => 'Langs',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 32,
                'created_at' => '2022-04-29 08:33:42',
                'updated_at' => '2022-04-29 08:33:42',
                'route' => 'voyager.langs.index',
                'parameters' => NULL,
            ),
            83 => 
            array (
                'id' => 88,
                'menu_id' => 1,
                'title' => 'Usefullinks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-cards',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 33,
                'created_at' => '2022-04-29 08:45:16',
                'updated_at' => '2022-04-29 08:45:16',
                'route' => 'voyager.usefullinks.index',
                'parameters' => NULL,
            ),
            84 => 
            array (
                'id' => 89,
                'menu_id' => 1,
                'title' => 'Footersocials',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 34,
                'created_at' => '2022-04-29 10:04:39',
                'updated_at' => '2022-04-29 10:04:39',
                'route' => 'voyager.footersocials.index',
                'parameters' => NULL,
            ),
            85 => 
            array (
                'id' => 90,
                'menu_id' => 7,
                'title' => '© 2022 Tərtibat Və Proqramlaşdırma Naxçıvan muxtar respublikası rabitə və yeni texnologiyalar Nazirliyiaaa',
                'url' => 'http://rabite.nmr.az/',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 35,
                'created_at' => '2022-04-29 10:21:49',
                'updated_at' => '2022-04-29 10:23:38',
                'route' => NULL,
                'parameters' => '',
            ),
            86 => 
            array (
                'id' => 91,
                'menu_id' => 1,
                'title' => 'Abouts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-company',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 36,
                'created_at' => '2022-04-29 12:31:21',
                'updated_at' => '2022-04-29 12:31:21',
                'route' => 'voyager.abouts.index',
                'parameters' => NULL,
            ),
            87 => 
            array (
                'id' => 92,
                'menu_id' => 1,
                'title' => 'Colleges',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 37,
                'created_at' => '2022-04-29 13:32:27',
                'updated_at' => '2022-04-29 13:32:27',
                'route' => 'voyager.colleges.index',
                'parameters' => NULL,
            ),
            88 => 
            array (
                'id' => 93,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 38,
                'created_at' => '2022-05-05 04:47:07',
                'updated_at' => '2022-05-05 04:47:07',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            89 => 
            array (
                'id' => 94,
                'menu_id' => 1,
                'title' => 'Faqs',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 39,
                'created_at' => '2022-05-05 12:28:37',
                'updated_at' => '2022-05-05 12:28:37',
                'route' => 'voyager.faqs.index',
                'parameters' => NULL,
            ),
            90 => 
            array (
                'id' => 95,
                'menu_id' => 1,
                'title' => 'Internationaldocuments',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-documentation',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 40,
                'created_at' => '2022-05-05 12:40:05',
                'updated_at' => '2022-05-05 12:40:05',
                'route' => 'voyager.internationaldocuments.index',
                'parameters' => NULL,
            ),
            91 => 
            array (
                'id' => 96,
                'menu_id' => 1,
                'title' => 'Legalacts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-zoom-in',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 41,
                'created_at' => '2022-05-05 12:56:54',
                'updated_at' => '2022-05-05 12:56:54',
                'route' => 'voyager.legalacts.index',
                'parameters' => NULL,
            ),
            92 => 
            array (
                'id' => 97,
                'menu_id' => 1,
                'title' => 'Decisionpresidia',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bookmark',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 42,
                'created_at' => '2022-05-05 13:21:00',
                'updated_at' => '2022-05-05 13:21:00',
                'route' => 'voyager.decisionpresidia.index',
                'parameters' => NULL,
            ),
            93 => 
            array (
                'id' => 98,
                'menu_id' => 1,
                'title' => 'Speeches',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-check-circle',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 43,
                'created_at' => '2022-05-05 13:40:29',
                'updated_at' => '2022-05-05 13:40:29',
                'route' => 'voyager.speeches.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}