<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FromArtisanMenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'İdarəetmə Paneli',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-05-13 05:23:08',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.media.index',
                'parameters' => 'null',
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'İstifadəçilər',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-05-13 05:23:45',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Rollar',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-05-13 05:22:57',
                'route' => 'voyager.roles.index',
                'parameters' => 'null',
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Alətlər paneli',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-05-13 05:57:46',
                'route' => 'voyager.menus.index',
                'parameters' => 'null',
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Verilənlər bazası',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.database.index',
                'parameters' => 'null',
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Kompas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.compass.index',
                'parameters' => 'null',
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.bread.index',
                'parameters' => 'null',
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Tənzimləmələr',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2022-04-27 18:17:11',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 2,
                'title' => 'Əsas səhİfə',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-home',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2022-04-27 19:39:33',
                'updated_at' => '2022-04-27 20:06:45',
                'route' => 'home',
                'parameters' => 'null',
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 2,
                'title' => 'Məhkəmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2022-04-27 19:43:05',
                'updated_at' => '2022-04-27 19:43:05',
                'route' => NULL,
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 2,
                'title' => 'Hüquqİ aktlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2022-04-27 19:43:32',
                'updated_at' => '2022-04-27 20:05:49',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 2,
                'title' => 'Məhkəmə sənədlərİ',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2022-04-27 19:43:48',
                'updated_at' => '2022-04-27 20:06:02',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 2,
                'title' => 'Mətbuat xidmətİ',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 19,
                'created_at' => '2022-04-27 19:44:10',
                'updated_at' => '2022-04-27 20:06:11',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 2,
                'title' => 'Hüquqİ maarİfləndİrmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 20,
                'created_at' => '2022-04-27 19:44:24',
                'updated_at' => '2022-04-27 20:06:26',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 3,
                'title' => 'home',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-04-28 05:33:40',
                'updated_at' => '2022-05-10 08:29:58',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 3,
                'title' => 'Məhkəmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-04-28 05:52:27',
                'updated_at' => '2022-04-28 07:34:00',
                'route' => 'court',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 3,
                'title' => 'Hüquqi aktlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-04-28 05:52:47',
                'updated_at' => '2022-05-19 06:28:23',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 3,
                'title' => 'Ümumi məlumat',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 1,
                'created_at' => '2022-04-28 05:53:07',
                'updated_at' => '2022-04-29 13:20:23',
                'route' => '\\about',
                'parameters' => 'null',
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 3,
                'title' => 'Məhkəmənin sədri',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 2,
                'created_at' => '2022-04-28 05:53:22',
                'updated_at' => '2022-05-05 07:15:13',
                'route' => '\\college',
                'parameters' => 'null',
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 3,
                'title' => 'Rəyasət heyəti',
                'url' => '',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 3,
                'created_at' => '2022-04-28 05:53:33',
                'updated_at' => '2022-05-05 07:42:09',
                'route' => 'https://courts.gov.az/az/nakhchivansupreme/board/Ryast-Heyti_5',
                'parameters' => 'null',
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 3,
                'title' => 'Hakimlər',
                'url' => '',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 4,
                'created_at' => '2022-04-28 07:36:58',
                'updated_at' => '2022-04-28 07:41:33',
                'route' => 'https://courts.gov.az/az/nakhchivansupreme/judges',
                'parameters' => 'null',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 3,
                'title' => 'Məhkəmənin strukturu',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 5,
                'created_at' => '2022-04-28 07:37:24',
                'updated_at' => '2022-05-17 18:48:40',
                'route' => '\\apparats',
                'parameters' => 'null',
            ),
            24 => 
            array (
                'id' => 25,
                'menu_id' => 3,
                'title' => 'Məhkəmə aparatı',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 6,
                'created_at' => '2022-04-28 07:42:28',
                'updated_at' => '2022-05-17 13:48:20',
                'route' => '\\structure',
                'parameters' => 'null',
            ),
            25 => 
            array (
                'id' => 26,
                'menu_id' => 3,
                'title' => 'Ali Məhkəmə - 90',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 7,
                'created_at' => '2022-04-28 07:42:59',
                'updated_at' => '2022-05-06 05:47:22',
                'route' => '\\supremecourt',
                'parameters' => 'null',
            ),
            26 => 
            array (
                'id' => 27,
                'menu_id' => 3,
                'title' => 'Azərbaycan Respublikasının hüquqi aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 19,
                'order' => 1,
                'created_at' => '2022-04-28 07:46:23',
                'updated_at' => '2022-05-05 12:57:15',
                'route' => '\\legalact',
                'parameters' => 'null',
            ),
            27 => 
            array (
                'id' => 28,
                'menu_id' => 3,
                'title' => 'Naxçıvan Muxtar Respublikasının hüquqi aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 19,
                'order' => 2,
                'created_at' => '2022-04-28 07:47:35',
                'updated_at' => '2022-04-28 07:48:51',
                'route' => 'http://huquqiaktlar.nakhchivan.az/Akts.aspx',
                'parameters' => 'null',
            ),
            28 => 
            array (
                'id' => 29,
                'menu_id' => 3,
                'title' => 'Beynəlxalq hüquqi sənədlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 19,
                'order' => 3,
                'created_at' => '2022-04-28 07:48:07',
                'updated_at' => '2022-05-05 12:44:10',
                'route' => '\\internationaldocument',
                'parameters' => 'null',
            ),
            29 => 
            array (
                'id' => 30,
                'menu_id' => 3,
                'title' => 'Məhkəmə sənədləri',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-04-28 07:49:32',
                'updated_at' => '2022-05-19 06:25:06',
                'route' => NULL,
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => 31,
                'menu_id' => 3,
                'title' => 'Rəyasət heyətinin qərarları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 30,
                'order' => 1,
                'created_at' => '2022-04-28 07:50:03',
                'updated_at' => '2022-05-05 13:23:59',
                'route' => '\\decisionpresidia',
                'parameters' => 'null',
            ),
            31 => 
            array (
                'id' => 32,
                'menu_id' => 3,
                'title' => 'Məhkəmə aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 30,
                'order' => 2,
                'created_at' => '2022-04-28 07:50:32',
                'updated_at' => '2022-05-10 08:39:10',
                'route' => 'https://e-mehkeme.gov.az/Public/Anonymizedecisions?courtid=113',
                'parameters' => 'null',
            ),
            32 => 
            array (
                'id' => 33,
                'menu_id' => 3,
                'title' => 'Avropa İnsan hüquqları məhkəməsinin qərarları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 30,
                'order' => 3,
                'created_at' => '2022-04-28 07:51:10',
                'updated_at' => '2022-05-10 08:39:42',
                'route' => 'https://hudoc.echr.coe.int/eng#{%22documentcollectionid2%22:[%22GRANDCHAMBER%22,%22CHAMBER%22]}',
                'parameters' => 'null',
            ),
            33 => 
            array (
                'id' => 34,
                'menu_id' => 3,
                'title' => 'Mətbuat xİdmətİ',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-04-28 07:53:32',
                'updated_at' => '2022-05-10 08:40:14',
                'route' => NULL,
                'parameters' => '',
            ),
            34 => 
            array (
                'id' => 35,
                'menu_id' => 3,
                'title' => 'Xəbərlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 1,
                'created_at' => '2022-04-28 07:53:55',
                'updated_at' => '2022-05-05 07:29:06',
                'route' => '/news',
                'parameters' => 'null',
            ),
            35 => 
            array (
                'id' => 36,
                'menu_id' => 3,
                'title' => 'Hesabatlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 2,
                'created_at' => '2022-04-28 07:54:23',
                'updated_at' => '2022-05-05 18:24:04',
                'route' => '\\report',
                'parameters' => 'null',
            ),
            36 => 
            array (
                'id' => 37,
                'menu_id' => 3,
                'title' => 'Çıxışlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 3,
                'created_at' => '2022-04-28 07:54:49',
                'updated_at' => '2022-05-05 13:38:41',
                'route' => '\\speech',
                'parameters' => 'null',
            ),
            37 => 
            array (
                'id' => 38,
                'menu_id' => 3,
                'title' => 'Foto materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 4,
                'created_at' => '2022-04-28 07:55:18',
                'updated_at' => '2022-05-05 19:08:21',
                'route' => '\\gallery',
                'parameters' => 'null',
            ),
            38 => 
            array (
                'id' => 39,
                'menu_id' => 3,
                'title' => 'Video materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 5,
                'created_at' => '2022-04-28 07:55:33',
                'updated_at' => '2022-05-05 19:10:37',
                'route' => '\\video',
                'parameters' => 'null',
            ),
            39 => 
            array (
                'id' => 40,
                'menu_id' => 3,
                'title' => 'Məqalələr',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 6,
                'created_at' => '2022-04-28 07:55:47',
                'updated_at' => '2022-05-05 19:18:22',
                'route' => '\\article',
                'parameters' => 'null',
            ),
            40 => 
            array (
                'id' => 41,
                'menu_id' => 3,
                'title' => 'Hüquqİ Maarİfləndİrmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2022-04-28 07:56:29',
                'updated_at' => '2022-05-10 08:43:55',
                'route' => NULL,
                'parameters' => '',
            ),
            41 => 
            array (
                'id' => 42,
                'menu_id' => 3,
                'title' => 'Sual-cavab',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 41,
                'order' => 1,
                'created_at' => '2022-04-28 07:57:05',
                'updated_at' => '2022-05-05 12:29:20',
                'route' => '\\faq',
                'parameters' => 'null',
            ),
            42 => 
            array (
                'id' => 43,
                'menu_id' => 3,
                'title' => 'Maarifləndirici materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 41,
                'order' => 2,
                'created_at' => '2022-04-28 07:57:22',
                'updated_at' => '2022-05-05 19:48:53',
                'route' => '\\educationmaterial',
                'parameters' => 'null',
            ),
            43 => 
            array (
                'id' => 44,
                'menu_id' => 3,
                'title' => 'Tədbirlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 41,
                'order' => 3,
                'created_at' => '2022-04-28 07:57:36',
                'updated_at' => '2022-05-05 19:27:07',
                'route' => '\\measures',
                'parameters' => 'null',
            ),
            44 => 
            array (
                'id' => 46,
                'menu_id' => 4,
                'title' => 'Məhkəmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-04-28 08:11:26',
                'updated_at' => '2022-05-10 08:26:15',
                'route' => NULL,
                'parameters' => '',
            ),
            45 => 
            array (
                'id' => 47,
                'menu_id' => 4,
                'title' => 'Məhkəmənin sədri',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 2,
                'created_at' => '2022-04-28 08:34:40',
                'updated_at' => '2022-05-07 08:11:23',
                'route' => '\\college',
                'parameters' => 'null',
            ),
            46 => 
            array (
                'id' => 48,
                'menu_id' => 4,
                'title' => 'Hüquqİ aktlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-04-28 08:34:56',
                'updated_at' => '2022-05-19 07:05:31',
                'route' => NULL,
                'parameters' => '',
            ),
            47 => 
            array (
                'id' => 49,
                'menu_id' => 4,
                'title' => 'Mətbuat xİdmətİ',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-04-28 08:35:14',
                'updated_at' => '2022-05-19 07:06:12',
                'route' => NULL,
                'parameters' => '',
            ),
            48 => 
            array (
                'id' => 51,
                'menu_id' => 4,
                'title' => 'Ümumi məlumat',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 1,
                'created_at' => '2022-04-28 08:36:02',
                'updated_at' => '2022-05-07 08:10:50',
                'route' => '\\about',
                'parameters' => 'null',
            ),
            49 => 
            array (
                'id' => 52,
                'menu_id' => 4,
                'title' => 'Rəyasət heyəti',
                'url' => '',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 3,
                'created_at' => '2022-04-28 10:01:40',
                'updated_at' => '2022-05-10 08:16:03',
                'route' => 'https://courts.gov.az/az/nakhchivansupreme/board/Ryast-Heyti_5',
                'parameters' => 'null',
            ),
            50 => 
            array (
                'id' => 53,
                'menu_id' => 4,
                'title' => 'Məhkəmə sənədlərİ',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-04-28 10:02:50',
                'updated_at' => '2022-05-19 07:05:51',
                'route' => NULL,
                'parameters' => '',
            ),
            51 => 
            array (
                'id' => 55,
                'menu_id' => 4,
                'title' => 'Hüquqİ maarİfləndİrmə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-04-28 10:03:36',
                'updated_at' => '2022-05-19 07:06:31',
                'route' => NULL,
                'parameters' => '',
            ),
            52 => 
            array (
                'id' => 56,
                'menu_id' => 4,
                'title' => 'Hakimlər',
                'url' => '',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 4,
                'created_at' => '2022-04-28 10:04:07',
                'updated_at' => '2022-05-10 08:16:12',
                'route' => 'https://courts.gov.az/az/nakhchivansupreme/judges',
                'parameters' => 'null',
            ),
            53 => 
            array (
                'id' => 57,
                'menu_id' => 4,
                'title' => 'Məhkəmənin strukturu',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 5,
                'created_at' => '2022-04-28 10:04:25',
                'updated_at' => '2022-05-19 08:06:06',
                'route' => '\\apparats',
                'parameters' => 'null',
            ),
            54 => 
            array (
                'id' => 58,
                'menu_id' => 4,
                'title' => 'Məhkəmə aparatı',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 6,
                'created_at' => '2022-04-28 10:04:50',
                'updated_at' => '2022-05-19 08:06:17',
                'route' => '\\structure',
                'parameters' => 'null',
            ),
            55 => 
            array (
                'id' => 59,
                'menu_id' => 4,
                'title' => 'Ali məhkəmə - 90',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 46,
                'order' => 7,
                'created_at' => '2022-04-28 10:05:17',
                'updated_at' => '2022-05-07 08:23:58',
                'route' => '\\supremecourt',
                'parameters' => 'null',
            ),
            56 => 
            array (
                'id' => 60,
                'menu_id' => 4,
                'title' => 'Azərbaycan Respublikasının hüquqi aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 48,
                'order' => 1,
                'created_at' => '2022-04-28 10:14:32',
                'updated_at' => '2022-05-07 08:24:28',
                'route' => '\\legalact',
                'parameters' => 'null',
            ),
            57 => 
            array (
                'id' => 61,
                'menu_id' => 4,
                'title' => 'Naxçıvan Muxtar Respublikasının hüquqi aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 48,
                'order' => 2,
                'created_at' => '2022-04-28 10:14:47',
                'updated_at' => '2022-05-07 08:24:52',
                'route' => 'http://huquqiaktlar.nakhchivan.az/Akts.aspx',
                'parameters' => 'null',
            ),
            58 => 
            array (
                'id' => 62,
                'menu_id' => 4,
                'title' => 'Beynəlxalq hüquqi sənədlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 48,
                'order' => 3,
                'created_at' => '2022-04-28 10:15:00',
                'updated_at' => '2022-05-07 08:25:13',
                'route' => '\\internationaldocument',
                'parameters' => 'null',
            ),
            59 => 
            array (
                'id' => 63,
                'menu_id' => 4,
                'title' => 'Rəyasət heyətinin qərarları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 53,
                'order' => 1,
                'created_at' => '2022-04-28 10:15:56',
                'updated_at' => '2022-05-07 08:30:30',
                'route' => '\\decisionpresidia',
                'parameters' => 'null',
            ),
            60 => 
            array (
                'id' => 64,
                'menu_id' => 4,
                'title' => 'Məhkəmə aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 53,
                'order' => 2,
                'created_at' => '2022-04-28 10:16:09',
                'updated_at' => '2022-05-10 08:18:10',
                'route' => 'https://e-mehkeme.gov.az/Public/Anonymizedecisions?courtid=113',
                'parameters' => 'null',
            ),
            61 => 
            array (
                'id' => 65,
                'menu_id' => 4,
                'title' => 'Avropa İnsan Hüquqları Məhkəməsinin qərarları',
                'url' => '',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 53,
                'order' => 3,
                'created_at' => '2022-04-28 10:16:23',
                'updated_at' => '2022-05-10 08:18:56',
                'route' => 'https://hudoc.echr.coe.int/eng#{%22documentcollectionid2%22:[%22GRANDCHAMBER%22,%22CHAMBER%22]}',
                'parameters' => 'null',
            ),
            62 => 
            array (
                'id' => 66,
                'menu_id' => 4,
                'title' => 'Xəbərlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 1,
                'created_at' => '2022-04-28 10:17:06',
                'updated_at' => '2022-05-10 08:19:48',
                'route' => '/news',
                'parameters' => 'null',
            ),
            63 => 
            array (
                'id' => 67,
                'menu_id' => 4,
                'title' => 'Hesabatlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 2,
                'created_at' => '2022-04-28 10:17:17',
                'updated_at' => '2022-05-10 08:20:19',
                'route' => '\\report',
                'parameters' => 'null',
            ),
            64 => 
            array (
                'id' => 68,
                'menu_id' => 4,
                'title' => 'Çıxışlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 3,
                'created_at' => '2022-04-28 10:17:49',
                'updated_at' => '2022-05-10 08:20:50',
                'route' => '\\speech',
                'parameters' => 'null',
            ),
            65 => 
            array (
                'id' => 69,
                'menu_id' => 4,
                'title' => 'Foto materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 4,
                'created_at' => '2022-04-28 10:18:02',
                'updated_at' => '2022-05-10 08:21:15',
                'route' => '\\gallery',
                'parameters' => 'null',
            ),
            66 => 
            array (
                'id' => 70,
                'menu_id' => 4,
                'title' => 'Video materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 5,
                'created_at' => '2022-04-28 10:18:17',
                'updated_at' => '2022-05-10 08:21:41',
                'route' => '\\video',
                'parameters' => 'null',
            ),
            67 => 
            array (
                'id' => 71,
                'menu_id' => 4,
                'title' => 'Məqalələr',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 6,
                'created_at' => '2022-04-28 10:18:34',
                'updated_at' => '2022-05-10 08:22:01',
                'route' => '\\article',
                'parameters' => 'null',
            ),
            68 => 
            array (
                'id' => 72,
                'menu_id' => 4,
                'title' => 'Sual-cavab',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 55,
                'order' => 1,
                'created_at' => '2022-04-28 10:19:51',
                'updated_at' => '2022-05-10 08:22:25',
                'route' => '\\faq',
                'parameters' => 'null',
            ),
            69 => 
            array (
                'id' => 73,
                'menu_id' => 4,
                'title' => 'Maarifləndirici materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 55,
                'order' => 2,
                'created_at' => '2022-04-28 10:20:06',
                'updated_at' => '2022-05-10 08:22:50',
                'route' => '\\educationmaterial',
                'parameters' => 'null',
            ),
            70 => 
            array (
                'id' => 74,
                'menu_id' => 4,
                'title' => 'Tədbirlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 55,
                'order' => 3,
                'created_at' => '2022-04-28 10:20:22',
                'updated_at' => '2022-05-10 08:23:09',
                'route' => '\\measures',
                'parameters' => 'null',
            ),
            71 => 
            array (
                'id' => 75,
                'menu_id' => 5,
                'title' => 'youtube',
                'url' => 'https://www.youtube.com/',
                'target' => '_blank',
                'icon_class' => 'fa-youtube',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 21,
                'created_at' => '2022-04-28 10:26:44',
                'updated_at' => '2022-04-28 10:42:04',
                'route' => NULL,
                'parameters' => '',
            ),
            72 => 
            array (
                'id' => 76,
                'menu_id' => 5,
                'title' => 'facebook',
                'url' => 'https://www.facebook.com/',
                'target' => '_blank',
                'icon_class' => 'fa-facebook-f',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 22,
                'created_at' => '2022-04-28 10:27:42',
                'updated_at' => '2022-04-28 10:51:57',
                'route' => NULL,
                'parameters' => '',
            ),
            73 => 
            array (
                'id' => 77,
                'menu_id' => 5,
                'title' => 'twitter',
                'url' => 'https://twitter.com/?lang=tr',
                'target' => '_blank',
                'icon_class' => 'fa-twitter',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 23,
                'created_at' => '2022-04-28 10:28:28',
                'updated_at' => '2022-04-28 10:42:21',
                'route' => NULL,
                'parameters' => '',
            ),
            74 => 
            array (
                'id' => 78,
                'menu_id' => 5,
                'title' => 'instagram',
                'url' => 'https://www.instagram.com/',
                'target' => '_blank',
                'icon_class' => 'fa-instagram',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 24,
                'created_at' => '2022-04-28 10:28:54',
                'updated_at' => '2022-04-28 10:42:37',
                'route' => NULL,
                'parameters' => '',
            ),
            75 => 
            array (
                'id' => 79,
                'menu_id' => 5,
                'title' => 'telegram',
                'url' => 'https://telegram.org/',
                'target' => '_blank',
                'icon_class' => 'fa-telegram',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 25,
                'created_at' => '2022-04-28 10:29:38',
                'updated_at' => '2022-04-28 10:42:52',
                'route' => NULL,
                'parameters' => '',
            ),
            76 => 
            array (
                'id' => 83,
                'menu_id' => 1,
                'title' => 'Əlaqə',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2022-04-28 18:34:28',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.contacts.index',
                'parameters' => 'null',
            ),
            77 => 
            array (
                'id' => 84,
                'menu_id' => 1,
                'title' => 'Vətəndaşlar üçün',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2022-04-29 06:03:24',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.forpersons.index',
                'parameters' => 'null',
            ),
            78 => 
            array (
                'id' => 85,
                'menu_id' => 1,
                'title' => 'Xidmətlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2022-04-29 06:22:54',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.services.index',
                'parameters' => 'null',
            ),
            79 => 
            array (
                'id' => 86,
                'menu_id' => 1,
                'title' => 'NMR Məhkəmələri',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-treasure',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2022-04-29 07:16:30',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.nmrcourts.index',
                'parameters' => 'null',
            ),
            80 => 
            array (
                'id' => 88,
                'menu_id' => 1,
                'title' => 'Faydalı Linklər',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-cards',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2022-04-29 08:45:16',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.usefullinks.index',
                'parameters' => 'null',
            ),
            81 => 
            array (
                'id' => 90,
                'menu_id' => 7,
                'title' => 'Tərtibat Və Proqramlaşdırma Naxçıvan muxtar respublikası rabitə və yeni texnologiyalar Nazirliyi',
                'url' => 'http://rabite.nmr.az/',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-04-29 10:21:49',
                'updated_at' => '2022-05-16 10:26:14',
                'route' => NULL,
                'parameters' => '',
            ),
            82 => 
            array (
                'id' => 93,
                'menu_id' => 1,
                'title' => 'Dinamik səhifələr',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2022-05-05 04:47:07',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.pages.index',
                'parameters' => 'null',
            ),
            83 => 
            array (
                'id' => 94,
                'menu_id' => 1,
                'title' => 'Tez-tez verilən suallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2022-05-05 12:28:37',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.faqs.index',
                'parameters' => 'null',
            ),
            84 => 
            array (
                'id' => 95,
                'menu_id' => 1,
                'title' => 'Beynəlxalq hüquqi sənədlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-documentation',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2022-05-05 12:40:05',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.internationaldocuments.index',
                'parameters' => 'null',
            ),
            85 => 
            array (
                'id' => 96,
                'menu_id' => 1,
                'title' => 'Azərbaycan Respublikasının hüquqi aktları',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-zoom-in',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2022-05-05 12:56:54',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.legalacts.index',
                'parameters' => 'null',
            ),
            86 => 
            array (
                'id' => 97,
                'menu_id' => 1,
                'title' => 'Rəyasət heyətinin qərarları',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bookmark',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2022-05-05 13:21:00',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.decisionpresidia.index',
                'parameters' => 'null',
            ),
            87 => 
            array (
                'id' => 98,
                'menu_id' => 1,
                'title' => 'Çıxışlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-check-circle',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2022-05-05 13:40:29',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.speeches.index',
                'parameters' => 'null',
            ),
            88 => 
            array (
                'id' => 99,
                'menu_id' => 1,
                'title' => 'Hesabatlar',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list-add',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 19,
                'created_at' => '2022-05-05 18:17:30',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.reports.index',
                'parameters' => 'null',
            ),
            89 => 
            array (
                'id' => 100,
                'menu_id' => 1,
                'title' => 'Foto qalereya',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-camera',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 20,
                'created_at' => '2022-05-05 19:07:19',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.galleries.index',
                'parameters' => 'null',
            ),
            90 => 
            array (
                'id' => 101,
                'menu_id' => 1,
                'title' => 'Video qalereya',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-video',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 21,
                'created_at' => '2022-05-05 19:13:05',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.videos.index',
                'parameters' => 'null',
            ),
            91 => 
            array (
                'id' => 102,
                'menu_id' => 1,
                'title' => 'Məqalələr',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 22,
                'created_at' => '2022-05-05 19:17:26',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.articles.index',
                'parameters' => 'null',
            ),
            92 => 
            array (
                'id' => 103,
                'menu_id' => 1,
                'title' => 'Tədbirlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tv',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 23,
                'created_at' => '2022-05-05 19:25:26',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.measures.index',
                'parameters' => 'null',
            ),
            93 => 
            array (
                'id' => 104,
                'menu_id' => 1,
                'title' => 'Maarifləndirici materiallar',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lightbulb',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 24,
                'created_at' => '2022-05-05 19:47:45',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.educationmaterials.index',
                'parameters' => 'null',
            ),
            94 => 
            array (
                'id' => 105,
                'menu_id' => 1,
                'title' => 'Ali Məhkəmə-90',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-window-list',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 25,
                'created_at' => '2022-05-06 05:15:06',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.supremecourts.index',
                'parameters' => 'null',
            ),
            95 => 
            array (
                'id' => 107,
                'menu_id' => 1,
                'title' => 'Rəyasət heyətinin qərarları',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-handle',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 26,
                'created_at' => '2022-05-06 08:33:52',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.appeals.index',
                'parameters' => 'null',
            ),
            96 => 
            array (
                'id' => 108,
                'menu_id' => 1,
                'title' => 'Sənədlərin nümunələri',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-browser',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 27,
                'created_at' => '2022-05-06 10:17:00',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.exampledocuments.index',
                'parameters' => 'null',
            ),
            97 => 
            array (
                'id' => 109,
                'menu_id' => 1,
                'title' => 'Nəşrlərin nümunələri',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-terminal',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 28,
                'created_at' => '2022-05-06 11:05:09',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.publications.index',
                'parameters' => 'null',
            ),
            98 => 
            array (
                'id' => 110,
                'menu_id' => 1,
                'title' => 'Elektron kitabxana',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-belt',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 29,
                'created_at' => '2022-05-06 11:20:45',
                'updated_at' => '2022-05-13 05:50:00',
                'route' => 'voyager.electronlibraries.index',
                'parameters' => 'null',
            ),
            99 => 
            array (
                'id' => 111,
                'menu_id' => 1,
                'title' => 'Naxçıvan MR Ali Məhkəməsinin elektron bazası',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-logbook',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 30,
                'created_at' => '2022-05-06 12:16:56',
                'updated_at' => '2022-05-13 05:50:57',
                'route' => 'voyager.nmrelectronlibraries.index',
                'parameters' => 'null',
            ),
            100 => 
            array (
                'id' => 112,
                'menu_id' => 1,
                'title' => 'Konstitusiya',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-edit',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 31,
                'created_at' => '2022-05-06 12:54:31',
                'updated_at' => '2022-05-13 05:51:28',
                'route' => 'voyager.constitutions.index',
                'parameters' => 'null',
            ),
            101 => 
            array (
                'id' => 113,
                'menu_id' => 1,
                'title' => 'Xəbərlər',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-cards',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 32,
                'created_at' => '2022-05-11 05:57:45',
                'updated_at' => '2022-05-13 05:51:53',
                'route' => 'voyager.news.index',
                'parameters' => 'null',
            ),
            102 => 
            array (
                'id' => 114,
                'menu_id' => 1,
                'title' => 'Məktub yazmaq qaydası',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 33,
                'created_at' => '2022-05-11 07:50:54',
                'updated_at' => '2022-05-13 06:01:09',
                'route' => 'voyager.applyonlines.index',
                'parameters' => 'null',
            ),
            103 => 
            array (
                'id' => 119,
                'menu_id' => 1,
                'title' => 'Ünvan',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-cursor',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 36,
                'created_at' => '2022-05-12 13:05:22',
                'updated_at' => '2022-05-13 19:33:44',
                'route' => 'voyager.adres.index',
                'parameters' => 'null',
            ),
            104 => 
            array (
                'id' => 121,
                'menu_id' => 8,
                'title' => 'Naxçıvan Muxtar Respublikası Ali Məhkəməsi',
                'url' => 'http://127.0.0.1:8000/',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 38,
                'created_at' => '2022-05-14 12:53:55',
                'updated_at' => '2022-05-14 12:53:55',
                'route' => NULL,
                'parameters' => '',
            ),
            105 => 
            array (
                'id' => 122,
                'menu_id' => 9,
                'title' => 'Axtar',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 39,
                'created_at' => '2022-05-14 13:02:22',
                'updated_at' => '2022-05-14 13:02:22',
                'route' => NULL,
                'parameters' => NULL,
            ),
            106 => 
            array (
                'id' => 123,
                'menu_id' => 1,
            'title' => 'Naxçıvan bu gün(slayd)',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-double-up',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 40,
                'created_at' => '2022-05-16 06:27:42',
                'updated_at' => '2022-05-23 07:15:08',
                'route' => 'voyager.slidertodays.index',
                'parameters' => 'null',
            ),
            107 => 
            array (
                'id' => 127,
                'menu_id' => 1,
                'title' => 'Məhkəmənin strukturu',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-cards',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 42,
                'created_at' => '2022-05-17 19:13:05',
                'updated_at' => '2022-05-23 07:14:18',
                'route' => 'voyager.apparats.index',
                'parameters' => 'null',
            ),
            108 => 
            array (
                'id' => 128,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-05-18 18:09:53',
                'updated_at' => '2022-05-18 18:10:52',
                'route' => NULL,
                'parameters' => '',
            ),
            109 => 
            array (
                'id' => 129,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 128,
                'order' => 1,
                'created_at' => '2022-05-18 18:10:46',
                'updated_at' => '2022-05-19 06:03:53',
                'route' => '\\about',
                'parameters' => 'null',
            ),
            110 => 
            array (
                'id' => 130,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 128,
                'order' => 2,
                'created_at' => '2022-05-18 18:11:24',
                'updated_at' => '2022-05-19 06:07:25',
                'route' => '\\college',
                'parameters' => 'null',
            ),
            111 => 
            array (
                'id' => 131,
                'menu_id' => 11,
                'title' => '',
                'url' => 'https://courts.gov.az/en/nakhchivansupreme/board/Prezidium_5',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 128,
                'order' => 3,
                'created_at' => '2022-05-18 18:12:23',
                'updated_at' => '2022-05-23 12:28:30',
                'route' => NULL,
                'parameters' => '',
            ),
            112 => 
            array (
                'id' => 132,
                'menu_id' => 11,
                'title' => '',
                'url' => 'https://courts.gov.az/en/nakhchivansupreme/judges',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 128,
                'order' => 4,
                'created_at' => '2022-05-18 18:13:02',
                'updated_at' => '2022-05-19 06:09:47',
                'route' => NULL,
                'parameters' => '',
            ),
            113 => 
            array (
                'id' => 133,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 128,
                'order' => 5,
                'created_at' => '2022-05-18 18:13:36',
                'updated_at' => '2022-05-19 07:39:27',
                'route' => '\\apparats',
                'parameters' => 'null',
            ),
            114 => 
            array (
                'id' => 134,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 128,
                'order' => 6,
                'created_at' => '2022-05-18 18:14:26',
                'updated_at' => '2022-05-19 07:39:43',
                'route' => '\\structure',
                'parameters' => 'null',
            ),
            115 => 
            array (
                'id' => 135,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-05-18 18:15:07',
                'updated_at' => '2022-05-18 18:15:15',
                'route' => NULL,
                'parameters' => '',
            ),
            116 => 
            array (
                'id' => 136,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 135,
                'order' => 1,
                'created_at' => '2022-05-19 05:49:42',
                'updated_at' => '2022-05-19 06:12:46',
                'route' => '\\legalact',
                'parameters' => 'null',
            ),
            117 => 
            array (
                'id' => 137,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 135,
                'order' => 2,
                'created_at' => '2022-05-19 05:51:40',
                'updated_at' => '2022-05-19 06:13:17',
                'route' => '\\internationaldocument',
                'parameters' => 'null',
            ),
            118 => 
            array (
                'id' => 138,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-05-19 05:52:36',
                'updated_at' => '2022-05-19 05:54:12',
                'route' => NULL,
                'parameters' => '',
            ),
            119 => 
            array (
                'id' => 139,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 138,
                'order' => 1,
                'created_at' => '2022-05-19 05:54:08',
                'updated_at' => '2022-05-19 06:15:17',
                'route' => '\\decisionpresidia',
                'parameters' => 'null',
            ),
            120 => 
            array (
                'id' => 140,
                'menu_id' => 11,
                'title' => '',
                'url' => 'https://e-mehkeme.gov.az/Public/Anonymizedecisions?courtid=113',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 138,
                'order' => 2,
                'created_at' => '2022-05-19 05:54:41',
                'updated_at' => '2022-05-19 06:15:57',
                'route' => NULL,
                'parameters' => '',
            ),
            121 => 
            array (
                'id' => 141,
                'menu_id' => 11,
                'title' => '',
                'url' => 'https://hudoc.echr.coe.int/eng#{%22documentcollectionid2%22:[%22GRANDCHAMBER%22,%22CHAMBER%22]}',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 138,
                'order' => 3,
                'created_at' => '2022-05-19 05:55:28',
                'updated_at' => '2022-05-19 06:16:32',
                'route' => NULL,
                'parameters' => '',
            ),
            122 => 
            array (
                'id' => 142,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-05-19 05:56:14',
                'updated_at' => '2022-05-19 05:56:54',
                'route' => NULL,
                'parameters' => '',
            ),
            123 => 
            array (
                'id' => 143,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 142,
                'order' => 1,
                'created_at' => '2022-05-19 05:56:49',
                'updated_at' => '2022-05-19 06:17:13',
                'route' => '/news',
                'parameters' => 'null',
            ),
            124 => 
            array (
                'id' => 144,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 142,
                'order' => 2,
                'created_at' => '2022-05-19 05:57:37',
                'updated_at' => '2022-05-19 06:17:37',
                'route' => '\\gallery',
                'parameters' => 'null',
            ),
            125 => 
            array (
                'id' => 145,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 142,
                'order' => 3,
                'created_at' => '2022-05-19 05:58:18',
                'updated_at' => '2022-05-19 06:18:22',
                'route' => '\\video',
                'parameters' => 'null',
            ),
            126 => 
            array (
                'id' => 146,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-05-19 06:00:21',
                'updated_at' => '2022-05-19 06:01:10',
                'route' => NULL,
                'parameters' => '',
            ),
            127 => 
            array (
                'id' => 147,
                'menu_id' => 11,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 146,
                'order' => 1,
                'created_at' => '2022-05-19 06:01:04',
                'updated_at' => '2022-05-19 06:18:54',
                'route' => '\\measures',
                'parameters' => 'null',
            ),
            128 => 
            array (
                'id' => 148,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-05-23 12:25:35',
                'updated_at' => '2022-05-23 12:26:31',
                'route' => NULL,
                'parameters' => '',
            ),
            129 => 
            array (
                'id' => 149,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 148,
                'order' => 1,
                'created_at' => '2022-05-23 12:26:28',
                'updated_at' => '2022-05-23 12:26:45',
                'route' => '\\about',
                'parameters' => 'null',
            ),
            130 => 
            array (
                'id' => 150,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 148,
                'order' => 2,
                'created_at' => '2022-05-23 12:27:27',
                'updated_at' => '2022-05-23 12:27:33',
                'route' => '\\college',
                'parameters' => NULL,
            ),
            131 => 
            array (
                'id' => 151,
                'menu_id' => 12,
                'title' => '',
                'url' => 'https://courts.gov.az/ru/nakhchivansupreme/board/Prezidium_5',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 148,
                'order' => 3,
                'created_at' => '2022-05-23 12:28:22',
                'updated_at' => '2022-05-23 12:28:46',
                'route' => NULL,
                'parameters' => '',
            ),
            132 => 
            array (
                'id' => 152,
                'menu_id' => 12,
                'title' => '',
                'url' => 'https://courts.gov.az/ru/nakhchivansupreme/judges',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 148,
                'order' => 4,
                'created_at' => '2022-05-23 12:29:04',
                'updated_at' => '2022-05-23 12:42:27',
                'route' => NULL,
                'parameters' => '',
            ),
            133 => 
            array (
                'id' => 153,
                'menu_id' => 12,
                'title' => '',
                'url' => '\\apparats',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 148,
                'order' => 5,
                'created_at' => '2022-05-23 12:29:39',
                'updated_at' => '2022-05-23 12:29:55',
                'route' => NULL,
                'parameters' => '',
            ),
            134 => 
            array (
                'id' => 154,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 148,
                'order' => 6,
                'created_at' => '2022-05-23 12:30:25',
                'updated_at' => '2022-05-23 12:30:41',
                'route' => '\\structure',
                'parameters' => NULL,
            ),
            135 => 
            array (
                'id' => 155,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-05-23 12:31:05',
                'updated_at' => '2022-05-23 12:32:16',
                'route' => NULL,
                'parameters' => '',
            ),
            136 => 
            array (
                'id' => 156,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 155,
                'order' => 1,
                'created_at' => '2022-05-23 12:32:02',
                'updated_at' => '2022-05-23 12:32:16',
                'route' => '\\legalact',
                'parameters' => NULL,
            ),
            137 => 
            array (
                'id' => 157,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 155,
                'order' => 2,
                'created_at' => '2022-05-23 12:32:46',
                'updated_at' => '2022-05-23 12:33:00',
                'route' => '\\internationaldocument',
                'parameters' => NULL,
            ),
            138 => 
            array (
                'id' => 158,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-05-23 12:33:25',
                'updated_at' => '2022-05-23 12:34:24',
                'route' => NULL,
                'parameters' => '',
            ),
            139 => 
            array (
                'id' => 159,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 158,
                'order' => 1,
                'created_at' => '2022-05-23 12:34:00',
                'updated_at' => '2022-05-23 12:34:24',
                'route' => '\\decisionpresidia',
                'parameters' => NULL,
            ),
            140 => 
            array (
                'id' => 160,
                'menu_id' => 12,
                'title' => '',
                'url' => 'https://hudoc.echr.coe.int/rus#{%22documentcollectionid2%22:[%22GRANDCHAMBER%22,%22CHAMBER%22]}',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 158,
                'order' => 3,
                'created_at' => '2022-05-23 12:34:51',
                'updated_at' => '2022-05-23 12:43:49',
                'route' => NULL,
                'parameters' => '',
            ),
            141 => 
            array (
                'id' => 161,
                'menu_id' => 12,
                'title' => '',
                'url' => 'https://e-mehkeme.gov.az/Public/Anonymizedecisions?courtid=113',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 158,
                'order' => 2,
                'created_at' => '2022-05-23 12:36:02',
                'updated_at' => '2022-05-23 12:36:09',
                'route' => NULL,
                'parameters' => '',
            ),
            142 => 
            array (
                'id' => 162,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-05-23 12:36:35',
                'updated_at' => '2022-05-23 12:38:09',
                'route' => NULL,
                'parameters' => '',
            ),
            143 => 
            array (
                'id' => 163,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 162,
                'order' => 1,
                'created_at' => '2022-05-23 12:37:07',
                'updated_at' => '2022-05-23 12:38:09',
                'route' => '\\news',
                'parameters' => NULL,
            ),
            144 => 
            array (
                'id' => 164,
                'menu_id' => 12,
                'title' => '',
                'url' => '\\gallery',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 162,
                'order' => 2,
                'created_at' => '2022-05-23 12:37:53',
                'updated_at' => '2022-05-23 12:38:11',
                'route' => NULL,
                'parameters' => '',
            ),
            145 => 
            array (
                'id' => 165,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 162,
                'order' => 3,
                'created_at' => '2022-05-23 12:38:38',
                'updated_at' => '2022-05-23 12:39:08',
                'route' => '\\video',
                'parameters' => NULL,
            ),
            146 => 
            array (
                'id' => 166,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-05-23 12:39:01',
                'updated_at' => '2022-05-23 12:39:08',
                'route' => NULL,
                'parameters' => '',
            ),
            147 => 
            array (
                'id' => 167,
                'menu_id' => 12,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 43,
                'created_at' => '2022-05-23 12:39:36',
                'updated_at' => '2022-05-23 12:39:36',
                'route' => '\\measures',
                'parameters' => NULL,
            ),
            148 => 
            array (
                'id' => 168,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-05-25 18:24:05',
                'updated_at' => '2022-05-25 18:25:43',
                'route' => NULL,
                'parameters' => '',
            ),
            149 => 
            array (
                'id' => 169,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 168,
                'order' => 1,
                'created_at' => '2022-05-25 18:24:39',
                'updated_at' => '2022-05-25 18:25:43',
                'route' => '\\about',
                'parameters' => NULL,
            ),
            150 => 
            array (
                'id' => 170,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 168,
                'order' => 2,
                'created_at' => '2022-05-25 18:25:24',
                'updated_at' => '2022-05-25 18:25:44',
                'route' => '\\college',
                'parameters' => NULL,
            ),
            151 => 
            array (
                'id' => 171,
                'menu_id' => 13,
                'title' => '',
                'url' => 'https://courts.gov.az/en/nakhchivansupreme/board/Prezidium_5',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 168,
                'order' => 3,
                'created_at' => '2022-05-25 18:26:04',
                'updated_at' => '2022-05-25 18:26:12',
                'route' => NULL,
                'parameters' => '',
            ),
            152 => 
            array (
                'id' => 172,
                'menu_id' => 13,
                'title' => '',
                'url' => 'https://courts.gov.az/en/nakhchivansupreme/judges',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 168,
                'order' => 4,
                'created_at' => '2022-05-25 18:26:41',
                'updated_at' => '2022-05-25 18:26:47',
                'route' => NULL,
                'parameters' => '',
            ),
            153 => 
            array (
                'id' => 173,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 168,
                'order' => 5,
                'created_at' => '2022-05-25 18:27:56',
                'updated_at' => '2022-05-25 18:29:24',
                'route' => '\\apparats',
                'parameters' => NULL,
            ),
            154 => 
            array (
                'id' => 174,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 168,
                'order' => 6,
                'created_at' => '2022-05-25 18:29:57',
                'updated_at' => '2022-05-25 18:30:04',
                'route' => '\\structure',
                'parameters' => NULL,
            ),
            155 => 
            array (
                'id' => 175,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-05-25 18:30:37',
                'updated_at' => '2022-05-25 18:31:20',
                'route' => NULL,
                'parameters' => '',
            ),
            156 => 
            array (
                'id' => 176,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 175,
                'order' => 1,
                'created_at' => '2022-05-25 18:31:14',
                'updated_at' => '2022-05-25 18:31:20',
                'route' => '\\legalact',
                'parameters' => NULL,
            ),
            157 => 
            array (
                'id' => 177,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 175,
                'order' => 2,
                'created_at' => '2022-05-25 18:31:56',
                'updated_at' => '2022-05-25 18:32:03',
                'route' => '\\internationaldocument',
                'parameters' => NULL,
            ),
            158 => 
            array (
                'id' => 178,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-05-25 18:35:54',
                'updated_at' => '2022-05-25 18:36:43',
                'route' => NULL,
                'parameters' => '',
            ),
            159 => 
            array (
                'id' => 179,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 178,
                'order' => 1,
                'created_at' => '2022-05-25 18:36:36',
                'updated_at' => '2022-05-25 18:36:43',
                'route' => '\\decisionpresidia',
                'parameters' => NULL,
            ),
            160 => 
            array (
                'id' => 180,
                'menu_id' => 13,
                'title' => '',
                'url' => 'https://e-mehkeme.gov.az/Public/Anonymizedecisions?courtid=113',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 178,
                'order' => 2,
                'created_at' => '2022-05-25 18:37:24',
                'updated_at' => '2022-05-25 18:37:32',
                'route' => NULL,
                'parameters' => '',
            ),
            161 => 
            array (
                'id' => 181,
                'menu_id' => 13,
                'title' => '',
                'url' => 'https://hudoc.echr.coe.int/eng#{%22documentcollectionid2%22:[%22GRANDCHAMBER%22,%22CHAMBER%22]}',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 178,
                'order' => 3,
                'created_at' => '2022-05-25 18:37:56',
                'updated_at' => '2022-05-25 18:43:05',
                'route' => NULL,
                'parameters' => '',
            ),
            162 => 
            array (
                'id' => 182,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-05-25 18:38:20',
                'updated_at' => '2022-05-25 18:43:05',
                'route' => NULL,
                'parameters' => '',
            ),
            163 => 
            array (
                'id' => 183,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 182,
                'order' => 1,
                'created_at' => '2022-05-25 18:42:48',
                'updated_at' => '2022-05-25 18:42:56',
                'route' => '/news',
                'parameters' => NULL,
            ),
            164 => 
            array (
                'id' => 184,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 182,
                'order' => 2,
                'created_at' => '2022-05-25 18:43:32',
                'updated_at' => '2022-05-25 18:43:39',
                'route' => '\\gallery',
                'parameters' => NULL,
            ),
            165 => 
            array (
                'id' => 185,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 182,
                'order' => 3,
                'created_at' => '2022-05-25 18:44:07',
                'updated_at' => '2022-05-25 18:44:14',
                'route' => '\\video',
                'parameters' => NULL,
            ),
            166 => 
            array (
                'id' => 186,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 44,
                'created_at' => '2022-05-25 18:44:33',
                'updated_at' => '2022-05-25 18:44:33',
                'route' => NULL,
                'parameters' => '',
            ),
            167 => 
            array (
                'id' => 187,
                'menu_id' => 13,
                'title' => '',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 45,
                'created_at' => '2022-05-25 18:45:03',
                'updated_at' => '2022-05-25 18:45:03',
                'route' => '\\measures',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}