<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FromArtisanPagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pages')->delete();
        
        \DB::table('pages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'author_id' => 6,
                'title' => 'Ümumi məlumat',
                'short_description' => NULL,
                'body' => '<h3 class="second-title" style="box-sizing: border-box; margin: 20px 0px 10px; font-weight: 500; line-height: 1.4; font-size: 1.66rem; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; color: #333333; padding: 0px; text-align: justify;">Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi apellyasiya instansiyası məhkəməsi kimi &ouml;z ərazi yurisdiksiyasına aid edilmiş birinci instansiya məhkəmələri tərəfindən baxılmış işlər &uuml;zrə məhkəmə aktlarından verilmiş apellyasiya şikayətləri və apellyasiya protestləri &uuml;zrə işlərə baxır. Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi m&uuml;lki kollegiyadan, inzibati kollegiyadan, kommersiya kollegiyasından və cinayət kollegiyadan ibarətdir.</h3>
<h2 class="about-title-se" style="box-sizing: border-box; margin: 25px 0px; font-weight: 500; line-height: 1.1; font-size: 1.9rem; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; color: #333333; padding: 0px;">NAX&Ccedil;IVAN MR ALİ MƏHKƏMƏSİNİN TARİXİ</h2>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi &ouml;lkəmizin məhkəmə orqanları sistemində &ouml;z&uuml;nəməxsus yer tutur. Məhkəmələr və hakimlər haqqında Azərbaycan Respublikasının 1997-ci il 10 iyun tarixli Qanununda Nax&ccedil;ıvan MR Ali Məhkəməsi apellyasiya instansiyası məhkəməsi kimi təsbit edilmişdir. Lakin digər apellyasiya məhkəmələrindən fərqli olaraq, Nax&ccedil;ıvan MR Ali Məhkəməsi Məhkəmələr və hakimlər haqqında Qanunun 52-ci maddəsinə əsasən həm də Nax&ccedil;ıvan Muxtar Respublikasında ali məhkəmə organı funksiyasını yerinə yetirir və bundan irəli gələn Nax&ccedil;ıvan Muxtar Respublikasının Konstitusiyası ilə nəzərdə tutulmuş konstitusiya nəzarəti &uuml;zrə səlahiyyətləri həyata ke&ccedil;irir (Nax&ccedil;ıvan Muxtar Respublikası Konstitusiyasının 16, 44-c&uuml; maddələri).</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi bu g&uuml;nədək uzun tarixi yol ke&ccedil;miş, bu tarix Nax&ccedil;ıvan Muxtar Respublikasının, b&uuml;t&ouml;vl&uuml;kdə Azərbaycanın tarixi ilə sıx bağlı olub, &ouml;lkənin və muxtar respublikanın m&uuml;xtəlif zaman kəsiyində yaşadığı d&ouml;vr&uuml; &ouml;z&uuml;ndə əks etdirmişdir.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">İlk dəfə Azərbaycan Demokratik Cumhuriyyəti d&ouml;vr&uuml;ndə (1918-1920) başlanılan məhkəmə orqanları sisteminin yaradılması prosesi milli hakimiyyətin s&uuml;gutu nəticəsində başa &ccedil;atdırılmamış qaldı.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Lakin, Sovet hakimiyyətinin qurulmasından az m&uuml;ddət sonra Azərbaycanda yenidən məhkəmə orqanlarının təşkilinə başlanıldı.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Azərbaycan SSR Mərkəzi İcraiyyə Komitəsinin 1922-ci il 09 dekabr tarixdə ke&ccedil;irilən 2-ci sessiyasında &laquo;Azərbaycan SSR Məhkəmə quruluşu haqqında&raquo; ilk Əsasnamə qəbul edildi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">1922-ci il 30 dekabr tarixdə SSRİ-nin yaradılması ilə əlaqədar digər d&ouml;vlət strukturlarında olduğu kimi Azərbaycan SSR məhkəmə orqanları sistemində də m&uuml;əyyən dəyişikliklər həyata ke&ccedil;irildi. 1924-c&uuml; il 29 oktyabr tarixdə &laquo;SSRİ m&uuml;ttəfiq respublikalarının məhkəmə quruluşunun əsasları haqqında&raquo; qanun qəbul edildikdən sonra buna uyğun olaraq Azərbaycan SSR MİK &ouml;z&uuml;n&uuml;n 1925-ci il 3 yanvar tarixli qanunu ilə Azərbaycan SSR Yuxarı Məhkəməsini Azərbaycan SSR Ali Məhkəməsinə &ccedil;evirdi və buna m&uuml;vafiq olaraq Nax&ccedil;ıvan MSSR-də fəaliyyət g&ouml;stərən b&ouml;lmə də artıq 3 oktyabr 1925-ci il tarixdən Ali Məhkəmənin Nax&ccedil;ıvan MSSR-də b&ouml;lməsi adlandırıldı.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Ali Məhkəmənin Nax&ccedil;ıvan MSSR-də fəaliyyət g&ouml;stərən b&ouml;lməsi həm onun səlahiyyətlərinə aid edilmiş cinayət və m&uuml;lki işlər &uuml;zrə birinci instansiya məhkəməsi olaraq, həm də əhatə etdiyi ərazidə təşkil olunmuş xalq məhkəmələri &uuml;&ccedil;&uuml;n yuxarı məhkəmə orqanı kimi təxminən 1934-c&uuml; ilin ortalarınadək fəaliyyət g&ouml;stərdi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Azərbaycan SSR MİK-nin və XKS-nin 23 avqust 1934-c&uuml; il tarixli qərarı ilə 6 iyul 1927-ci il tarixdən etibarən respublikada məhkəmə quruluşu məsələlərini tənzimləyən Əsasnaməyə bir sıra dəyişikliklər edildli. Həmin dəyişikliklərdən biri də Azərbaycan SSR Ali Məhkəməsinin Nax&ccedil;ıvan MSSR-də fəaliyyət g&ouml;stərən b&ouml;lməsinin ləğv edilməsi və onun əvəzinə Nax&ccedil;ıvan MSSR Baş Məhkəməsinin yaradılması idi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Qeyd olunan tarixdən yaradılan, 1937-ci ildə Azərbaycan SSR-in yeni Konstitusiyasının qəbul edilməsindən sonra Nax&ccedil;ıvan MSSR Ali Məhkəməsi adını daşıyan məhkəmə m&uuml;xtəlif vaxtlarda m&uuml;vafiq qanunvericiliyin dəyişilməsinə baxmayaraq, b&uuml;t&uuml;n sovet d&ouml;vr&uuml; ərzində demək olar ki, ciddi dəyişikliyə uğramadı və ona aid edilmiş işlərə birinci və yuxarı instansiya məhkəməsi qismində baxmaq, həm&ccedil;inin onun fəaliyyəti dairəsində olan məhkəmələr &uuml;zərində məhkəmə nəzarətini həyata ke&ccedil;irmək funksiyalarıni saxladı.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">SSRİ-nin s&uuml;gutundan az m&uuml;ddət əvvəl 1990-cı il 26 iyun tarixdə qəbul edilən &laquo;Azərbaycan SSR-də məhkəmə quruluşu haqqında&raquo; yeni qanun bu sahədə bəzi dəyişkliklərin həyata ke&ccedil;irilməsini nəzərdə tuturdu.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Lakin həmin d&ouml;vrdə SSRİ-də, o c&uuml;mlədən Azərbaycanda cərayan edən hadisələr, ən başlıcası 18 oktyabr 1991-ci ildə Azərbaycanın d&ouml;vlət m&uuml;stəqilliyini əldə etməsi məhkəmə quruluşunun, ədalət m&uuml;hakiməsi qaydalarının daha geniş və k&ouml;kl&uuml; şəkildə dəyişdirilməsini tələb edirdi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Buna baxmayaraq, digər sahələrdə olduğu kimi, məhkəmə orqanları sistemində də həmin illərdə aparılan dəyişikliklər yetərli deyildi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Ancaq 1993-c&uuml; ildə xalqın &uuml;mummilli lideri m&ouml;htərəm Heydər Əliyevin hakimiyyətə qayıdışı ilə bu islahatların aparlması &uuml;&ccedil;&uuml;n real şərait yarandı və Prezident H.Əliyevin bilavasitə rəhbərliyi ilə Azərbaycan Respublikasının m&uuml;stəqil, h&uuml;quqi d&ouml;vlət kimi təşəkk&uuml;l tapmasını təmin edə biləcək məhkəmə islahatlarına başlanıldı.s</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Bu islahatların b&uuml;n&ouml;vrəsində m&ouml;htərəm Heydər Əliyevin rəhbərliyi ilə hazırlanmış 12 noyabr 1995-ci ildə &uuml;mumxalq səsverməsi yolu ilə qəbul edilmiş m&uuml;stəqil Azərbycan Respublikasının Konstitusiyası və onun əsasında 10 iyun 1997-ci ildə qəbul edilən &laquo;Məhkəmələr və hakimlər haqqında&raquo; Azərbaycan Respublikasının Qanunu dayanır.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&laquo;Məhkəmələr və Hakimlər haqqında&raquo; 10 iyun 1997-ci il tarixli Qanun Azərbaycan Respublikasında &uuml;&ccedil;pilləli məhkəmə sistemini bərqərar etdi və m&uuml;vafiq Məcəllələr, o c&uuml;mlədən Azərbaycan Respublikasının M&uuml;lki-Prosessual, Cinayət-Prosessual Məcəllələri qəbul edildikdən sonra 2000-ci ilin sentyabr ayından bu sistem real olaraq fəaliyyət g&ouml;stərməyə başladı.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Qanuna g&ouml;rə bu &uuml;&ccedil;pilləli sistem daxilində Nax&ccedil;ıvan MR Ali Məhkəməsinin yeri həm birinci instansiya, həm də ikinci-apellyasiya instansiyası məhkəməsi kimi m&uuml;əyyən edildi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Bu təyinata uyğun olaraq Ali Məhkəmənin tərkibində qanunla onun səlahiyyətlərinə aid edilmiş ağır cinayət işlərinə baxan ağır cinayətlərə dair işlər &uuml;zrə birinci instansiya kollegiyası, muxtar respublikanın ərazisində fəaliyyət g&ouml;stərən rayon (şəhər) məhkəmələrinin cinayət işləri və inzibati xətalara dair materiallar eləcə də m&uuml;lki işlər &uuml;zrə qanuni q&uuml;vvəyə minməmiş qərarlarından verilən apellyasiya şikayətlərinə və protestlərinə apellyasiya məhkəməsi qismində baxan cinayət işləri və inzibati xətalara dair işlər &uuml;zrə, eləcə də m&uuml;lki işlər &uuml;zrə apellyasiya kollegiyaları yaradıldı.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Azərbaycan Respublikası Prezidentinin 17 iyun 1999-cu il tarixli Fərmanına əsasən Nax&ccedil;ıvan MR Ali Məhkəməsinin hakimlərinin sayı 14 nəfər m&uuml;əyyən olundu və 2000-ci ilin sentyabrından 2003-c&uuml; ilin yanvarınadək məhkəmə hakim heyəti ilə tam komplektləşdirildi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">2000-ci ilin sentyabrından &ouml;tən d&ouml;vr ərzində bu formada təşkil olunmuş Nax&ccedil;ıvan MR Ali Məhkəməsinin, &uuml;mumiyyətlə Azərbaycanın b&uuml;t&uuml;n məhkəmə orqanlarının fəaliyyəti &uuml;&ccedil;pilləli məhkəmə sisteminin sovet d&ouml;vr&uuml;ndə və 2000-ci ilin sentyabr ayınadək Azərbaycan Respublikasında m&ouml;vcud olan ikipilləli məhkəmə sistemi ilə m&uuml;qayisədə daha m&uuml;tərəqqi məhkəmə quruluşu forması olduğunu s&uuml;but etdi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Lakin, bir tərəfdən Azərbaycan Respublikasında gedən inkişaf prosesləri və Azərbaycan Respublikasının Avropa ailəsinə, n&uuml;fuzlu beynəlxalq təşkilatlara daha sıx inteqrasiyası, digər tərəfdən Azərbaycan Respublikasının Apellyasiya və İqtisad məhkəmələrinin b&ouml;lgələrdən uzaqda - Bakı şəhərində təşkil olunmasından t&ouml;rəyən &ccedil;ətinliklər məhkəmə quruluşunda dəyişikliklərin edilməsini bir zərurət kimi meydana gətirdi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Həmin məhkəmələrin b&ouml;lgələrdən &ccedil;ox uzaqda yerləşməsi ilə bağlı yaranan problemlər Nax&ccedil;ıvan Muxtar Respublikasına m&uuml;nasibətdə &ouml;z&uuml;n&uuml; daha qabarıq şəkildə biruzə verirdi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&Ccedil;&uuml;nki, birinci instansiya məhkəmələri kimi fəaliyyət g&ouml;stərən Nax&ccedil;ıvan MR Ali Məhkəməsinin ağır cinayətlərə dair işlər &uuml;zrə kollegiyasının, Nax&ccedil;ıvan Muxtar Respublikasının Hərbi Məhkəməsinin və Nax&ccedil;ıvan MR İqtisad Məhkəməsinin qərarlarından verilən protest və şikayətlərə m&uuml;vafiq olaraq Azərbaycan Respublikasının Apellyasiya Məhkəməsində və Azərbaycan Respublikasının İqtisad Məhkəməsində baxılırdı. Nax&ccedil;ıvan Muxtar Respublikasına qarşı Ermənistan tərəfindən tətbiq olunan blokada isə muxtar respublikada yaşayan vətəndaşlarımızın həmin məhkəmələrdə baxılan işlərlə əlaqədar Bakı şəhərinə gedib-gəlmələri &uuml;&ccedil;&uuml;n &ccedil;ox ciddi əngəllər t&ouml;rədirdi.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Azərbaycan Respublikasının 30 dekabr 2005-ci il tarixli Qanunu ilə Məhkəmələr və hakimlər haqqında Qanuna, Azərbaycan Respublikasının bəzi qanunvericilik aktlarına dəyişikliklər və əlavələr edilməsi barədə Azərbaycan Respublikasının 2007-ci il 16 iyun tarixli Qanunu ilə m&uuml;vafiq prosesual qanunvericiliyə əlavə və dəyişikliklərin edilməsi və Azərbaycan Respublikası Prezidenti tərəfindən məhkəmə hakimiyyətinin m&uuml;asirləşdirilməsi məsələlərinə həsr olunmuş 19 yanvar 2006-cı il tarixli Fərmanın verilməsi nəticəsində məhkəmə islahatları n&ouml;vbəti mərhələyə y&uuml;ksəldi və bu mərhələdə Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi də &ccedil;ox ciddi, m&uuml;tərəqqi dəyişikliklərə uğradı.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Prosessual h&uuml;quq normalarının dəyişilməsini nəzərdə tutan 2007-ci il 16 iyun tarixli Qanunun 16 iyul 2009-cu ildə q&uuml;vvəyə minməsilə Nax&ccedil;ıvan Muxtar Respublikasında ayrıca Ağır Cinayətlərə Dair İşlər &uuml;zrə Məhkəmə yaradıldı və bununla əlaqədar Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsinin tərkibində olan Ağır Cinayətlərə Dair İşlər &uuml;zrə I instansiya kollegiyası ləğv olundu. Eyni zamanda Ali Məhkəmədə əvvəldən m&ouml;vcud olan M&uuml;lki işlər &uuml;zrə kollegiyadan və Cinayət işləri və inzibati xətalara dair işlər &uuml;zrə kollegiyadan savayı daha iki struktur - İqtisadi m&uuml;bahisələrə dair işlər &uuml;zrə kollegiya və Hərbi məhkəmələrin işləri &uuml;zrə kollegiya yaradıldı.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Yeni kollegiyaların yaradılmasından sonra 2009-cu ilin ilul ayından etibarən artıq Nax&ccedil;ıvan Muxtar Respublikasının Hərbi Məhkəməsinin baxdığı işlər (o c&uuml;mlədən ağır cinayətlərlə bağlı işlər) &uuml;zrə &ccedil;əxarılmış qərarlardan verilən şikayət və protestlərə həm&ccedil;inin Nax&ccedil;ıvan MR İqtisad Məhkəməsinin qərarlarından verilən şikayətlərə m&uuml;vafiq olaraq Hərbi məhkəmələrin işləri &uuml;zrə kollegiyada və İqtisadi m&uuml;bahisələrə dair işlər &uuml;zrə kollegiyada baxılır. Ağır Cinayətlərə dair İşlər &Uuml;zrə Nax&ccedil;ıvan Muxtar Respublikası Məhkəməsinin &ccedil;ıxardığı qərarlardan verilən şikayət və protestlərə isə Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin cinayət işləri və inzibati xətalara dair işlər &uuml;zrə kollegiyasında baxılır.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Bu yeniliklər Ali Məhkəmə tərəfindən işlərə birinci instansiya gaydasında baxılmasını istisna edir və Ali Məhkəmənin sırf apellyasiya instansiyası məhkəməsi kimi fəaliyyət g&ouml;stərməsini nəzərdə tutur.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Bununla yanaşı qanunvericiliyə gətirilən yeniliklər Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin Nax&ccedil;ıvan MR Konstitusiyası ilə təsbit edilən muxtar respublikada konstitusiya nəzarətinin həyata ke&ccedil;irilməsi ilə bağlı funksiyalarına toxunmamışdır.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Məhkəm h&uuml;quq islahatlarının davamı kimi Məhkəmələr və hakimlər haqqında və Məhkəmə-H&uuml;quq Şurası haqqında Azərbaycan Respublikasının qanunlarına dəyişikliklər və əlavələr edilməsi barədə Azərbaycan Respublikasının 22 iyun 2010-cu il tarixli qanununa əsasən Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsinin kollegiyalarının adları dəyişdirilərək m&uuml;lki kollegiya, inzibati-iqtisadi kollegiya, cinayət kollegiyası və hərbi kollegiya adlandırılmışdır. &ldquo;Məhkəmələr və hakimlər haqqında&rdquo; Azərbaycan Respublikasının Qanununda dəyişiklik edilməsi barədə 9 iyul 2019-cu il tarixli Qanunla Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi m&uuml;lki kollegiyadan, kommersiya kollegiyasından, inzibati kollegiyadan və cinayət kollegiyasından ibarət tərkibdə fəaliyyət g&ouml;stərir.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Muxtar Respublikanın Ali Məhkəməsində &laquo;Məhkəmələr və hakimlər haqqında&raquo; Qanununun 54-c&uuml; maddəsinə əsasən Rəyasət Heyəti fəaliyyət g&ouml;stərir.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Rəyasət Heyətinin tərkibinə Ali Məhkəmənin sədri, onun m&uuml;avini və kollegiya sədrləri daxildir.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Qanuna g&ouml;rə Rəyasət Heyəti ədalət m&uuml;hakiməsi funksiyasını yerinə yetirmir və qanunla onun səlahiyyətlərinə aid edilmiş məhkəmənin fəaliyyətinin təmin edilməsi ilə bağlı digər məsələləri həll edir, o c&uuml;mlədən hakimləri kollegiyalar &uuml;zrə b&ouml;l&uuml;şd&uuml;r&uuml;r, məhkəmə təcr&uuml;bəsinin &uuml;mumiləşdirilməsi və məhkəmə statistikasının təhlili barədə materiallara baxır, qanunvericilik aktlarının d&uuml;zg&uuml;n tətbiq edilməsi barədə muxtar respublikanın rayon (şəhər) məhkəmələrinə metodiki k&ouml;mək g&ouml;stərir, Nax&ccedil;ıvan Muxtar Respublikasının Ali Məhkəməsi yanında Elmi-Məsləhət Şurasının əsasnaməsini və tərkibini təsdiq edir və bir sıra başqa məsələləri həll edir.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Elmi-Məsləhət Şurasının Əsasnaməsi və tərkibi Ali Məhkəmənin Rəyasət Heyətinin qərarı ilə təsdiq edilmiş və 2004-c&uuml; ildən Şura fəaliyyətə başlamışdır.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Nax&ccedil;ıvan Muxtar Respublikasının digər məhkəmələri kimi, Ali Məhkəmənin də fəaliyyətinin m&uuml;asir tələblər səviyyəsində təşkil olunmasında Nax&ccedil;ıvan Muxtar Respublikasında h&uuml;quq institutlarının inkişafı haqqında Azərbaycan Respublikası Prezidentinin 2 noyabr 2006-cı il tarixli Fərmanının b&ouml;y&uuml;k rolu olmuşdur.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Muxtar respublikada qısa m&uuml;ddət ərzində bu Fərmanın realizə edilməsi təmin olunmuş və artıq 2007-ci ilin noyabr ayının 29-da Nax&ccedil;ıvan Muxtar Respublikası Ali Məclisi Sədrinin iştirakı ilə Ali Məhkəmənin yeni inzibati binası istifadəyə verilmişdir.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Nax&ccedil;ıvan şəhərinin mərkəzində yerləşən bu g&ouml;rkəmli binada hakimlərin, məhkəmə aparatı iş&ccedil;ilərinin keyfiyyətli və səmərəli fəaliyyət g&ouml;stərməsi &uuml;&ccedil;&uuml;n zəruri şərait y&uuml;ksək səviyyədə təmin edilmişdir.</p>
<p class="about-text" style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; font-size: 1.65rem; text-align: justify; color: #333333; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Bir tərəfdən qanunvericiliyə gətirilən yeniliklər, digər tərəfdən isə məhkəmələrin maddi təminat məsələlərinə g&ouml;stərilən diqqət, o c&uuml;mlədən hakimlərin, məhkəmə personalının iş şəraitinin m&uuml;asir meyarlar səviyyəsinə &ccedil;atdırılması Nax&ccedil;ıvan Muxtar Respublikası Ali Məhkəməsi tərəfindən ədalət m&uuml;hakiməsinin həyata ke&ccedil;irilməsi &uuml;zrə vəzifələrinin keyfiyyətlə yerinə yetirilməsinə, insan h&uuml;quq və azadlıglarının səmərəli şəkildə m&uuml;dafiə olunmasına xidmət edir.</p>',
                'image' => NULL,
                'slug' => 'about',
                'redirect_to' => 0,
                'external_link' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'status' => 'ACTIVE',
                'created_at' => '2022-05-05 05:01:00',
                'updated_at' => '2022-05-05 05:04:45',
            ),
        ));
        
        
    }
}